rehearsal-js/rehearsal-js

packages/diagnostic/README.md, packages/diagnostic/package.json, packages/diagnostic/src/comments.ts, packages/diagnostic/src/diagnose.ts, packages/diagnostic/src/diagnostic-service.ts, packages/diagnostic/src/index.ts, packages/diagnostic/test/diagnose.test.ts, packages/diagnostic/test/fixtures/app/.gitignore, packages/diagnostic/test/fixtures/app/first.ts.input, packages/diagnostic/test/fixtures/app/first.ts.output, packages/diagnostic/test/fixtures/app/second.ts.input, packages/diagnostic/test/fixtures/app/second.ts.output, packages/diagnostic/test/fixtures/app/tsconfig.json, packages/diagnostic/tsconfig.json, yarn.lock
Created a package @rehearsal/diagnostic with base configs.
Implementation of the package will come in the next PR.
=> refactor: init @rehearsal/diagnostic package

packages/diagnostic/src/cli.ts
Add types for diagnose CLI options
=>  refactor: types for diagnose CLI options

packages/diagnostic/package.json, packages/diagnostic/test/diagnose.test.ts
Found that I forgot to configure cli command for the package.
Plus fix the typo.
=> fix: @rehearsal/diagnostic cli config + fix typo

yarn.lock
Reverts rehearsal-js/rehearsal-js#130
=> Revert "chore: update yarn.lock"

packages/diagnostic/test/fixtures/diagnose/.rehearsal-diagnostics-only.json.output, packages/diagnostic/test/fixtures/diagnose/.rehearsal-diagnostics.json.output, packages/diagnostic/test/fixtures/diagnose/first.ts.input, packages/diagnostic/test/fixtures/diagnose/first.ts.output, packages/migrate/src/plugins/diagnostics-autofix.plugin.ts, packages/migrate/src/transforms/2322-fix-transform.ts, packages/migrate/test/fixtures/migrate/.rehearsal-report.output.json, packages/migrate/test/fixtures/migrate/.rehearsal-report.output.md, packages/migrate/test/fixtures/migrate/first.ts.input, packages/migrate/test/fixtures/migrate/first.ts.output, packages/migrate/test/migrate.test.ts
Add the transformer for 2322. We may add more logic later. Also revise the test.
=> feat: add placeholder transformer for TS2322 error code 

packages/cli/test/commands/ts.test.ts, packages/migrate/src/plugins/diagnostics-autofix.plugin.ts, packages/migrate/src/transforms/2322-fix-transform.ts, packages/migrate/src/transforms/6133-fix-transform.ts, packages/migrate/test/fixtures/migrate/.rehearsal-report.output.json, packages/migrate/test/fixtures/migrate/.rehearsal-report.output.md, packages/migrate/test/fixtures/migrate/2322.ts.input, packages/migrate/test/fixtures/migrate/2322.ts.output, packages/migrate/test/fixtures/migrate/6133.ts.input, packages/migrate/test/fixtures/migrate/6133.ts.output, packages/migrate/test/fixtures/migrate/first.ts.output, packages/migrate/test/migrate.test.ts
I experimented several ways to implement conditional hint and found this one more useful.
We can rename function from `fix` to `run` or something else, but the benefit of doing hints this way - conditions will be already described inside the `fix` function which can help when time to add the `fix` logic comes.
=> feat: conditional hints

packages/migrate/src/helpers/typescript-ast.ts, packages/migrate/src/interfaces/fix-transform.ts, packages/migrate/src/interfaces/plugin.ts, packages/migrate/src/migrate.ts, packages/migrate/src/plugins/diagnostics-autofix.plugin.ts, packages/migrate/src/plugins/empty-lines-preserve.plugin.ts, packages/migrate/src/plugins/empty-lines-restore.plugin.ts, packages/migrate/src/plugins/lint.plugin.ts, packages/migrate/src/transforms/2322-fix-transform.ts, packages/migrate/src/transforms/6133-fix-transform.ts
This PR allows each plugin to update multiple files.
=> feat: Allow multiple file updates per plugin call

packages/migrate/package.json, packages/migrate/src/helpers/strings.ts, packages/migrate/src/helpers/typescript-ast.ts, packages/migrate/src/migrate.ts, packages/migrate/src/plugins/diagnostics-autofix.plugin.ts, packages/migrate/src/transforms/6133-fix-transform.ts, packages/migrate/test/fixtures/migrate/.gitignore, packages/migrate/test/fixtures/migrate/.rehearsal-report.output.json, packages/migrate/test/fixtures/migrate/.rehearsal-report.output.md, packages/migrate/test/fixtures/migrate/6133.ts.output, packages/migrate/test/fixtures/migrate/first.ts.output, packages/migrate/test/fixtures/migrate/react.tsx.input, packages/migrate/test/fixtures/migrate/react.tsx.output, packages/migrate/test/fixtures/migrate/tsconfig.json, packages/migrate/test/migrate.test.ts, yarn.lock
- use correct comments' style inside JSX text
- fix global modules resolutions in tests
- refactor helpers
=> fix: use correct comments' style inside JSX text, modules resolutions in tests

packages/migrate/src/helpers/typescript-ast.ts, packages/migrate/src/plugins/diagnostics-autofix.plugin.ts, packages/migrate/src/transforms/2571-fix-transform.ts, packages/migrate/test/fixtures/migrate/.rehearsal-report.output.json, packages/migrate/test/fixtures/migrate/.rehearsal-report.output.md, packages/migrate/test/fixtures/migrate/2571.ts.input, packages/migrate/test/fixtures/migrate/2571.ts.output, packages/migrate/test/migrate.test.ts
Fix for TS2571 Object is of type '{0}'.
=> feat: Fix for TS2571 Object is of type '{0}'.

packages/cli/src/commands/ts.ts, packages/migrate/src/interfaces/plugin.ts, packages/migrate/src/migrate.ts, packages/migrate/src/plugins/diagnostics-autofix.plugin.ts, packages/migrate/src/plugins/empty-lines-preserve.plugin.ts, packages/migrate/src/plugins/empty-lines-restore.plugin.ts, packages/migrate/src/plugins/index.ts, packages/migrate/src/plugins/lint.plugin.ts, packages/migrate/src/transforms/2322-fix-transform.ts, packages/migrate/src/transforms/index.ts, packages/reporter/src/reporter.ts
This PR adds some missing types in the reporter package and cleanup on internal imports
=> chore: report types and cleanup internal imports

packages/migrate/src/helpers/transform-utils.ts, packages/migrate/src/plugins/diagnostics-autofix.plugin.ts, packages/migrate/src/transforms/4082-fix-transform.ts, packages/migrate/src/transforms/index.ts, packages/migrate/test/fixtures/migrate/.rehearsal-report.output.json, packages/migrate/test/fixtures/migrate/.rehearsal-report.output.md, packages/migrate/test/fixtures/migrate/4082-1-import.tsx.input, packages/migrate/test/fixtures/migrate/4082-1-import.tsx.output, packages/migrate/test/fixtures/migrate/4082-1.tsx.input, packages/migrate/test/fixtures/migrate/4082-1.tsx.output, packages/migrate/test/fixtures/migrate/4082-2-import.tsx.input, packages/migrate/test/fixtures/migrate/4082-2-import.tsx.output, packages/migrate/test/fixtures/migrate/4082-2.tsx.input, packages/migrate/test/fixtures/migrate/4082-2.tsx.output
This PR fixes TS4082 with the diagnostic message of the following:
"Default export of the module has or is using private name '{0}'."
=> feat: fix TS4082

.mocharc.json, packages/migrate/test/migrate.test.ts
Fix global `yarn test` failing
=> Increase global tests timeout

packages/migrate/src/transforms/4082-fix-transform.ts, packages/utils/test/test-service.ts, packages/utils/test/tsc-utils/getTypeDeclarationFromTypeSymbol.test.ts, packages/utils/tsconfig.json
This PR fixes a bug in TS4082 transform, plus a few minor issues.
=> fix: bug in TS4082 transform

.eslintrc.js, packages/cli/src/commands/ts.ts, packages/cli/src/index.ts, packages/diagnostic/src/diagnose.ts, packages/diagnostic/src/diagnostic-reporter.ts, packages/diagnostic/src/diagnostic-service.ts, packages/diagnostic/src/index.ts, packages/diagnostic/test/diagnose.test.ts, packages/migrate/src/index.ts, packages/migrate/src/interfaces/fix-transform.ts, packages/migrate/src/migrate.ts, packages/migrate/src/plugins/diagnostics-autofix.plugin.ts, packages/migrate/src/plugins/empty-lines-preserve.plugin.ts, packages/migrate/src/plugins/empty-lines-restore.plugin.ts, packages/migrate/src/plugins/index.ts, packages/migrate/src/plugins/lint.plugin.ts, packages/migrate/src/transforms/2322-fix-transform.ts, packages/migrate/src/transforms/2345-fix-transform.ts, packages/migrate/src/transforms/2571-fix-transform.ts, packages/migrate/src/transforms/2790-fix-transform.ts, packages/migrate/src/transforms/4082-fix-transform.ts, packages/migrate/src/transforms/6133-fix-transform.ts, packages/migrate/src/transforms/index.ts, packages/migrate/test/migrate.test.ts, packages/reporter/src/index.ts, packages/service/src/index.ts, packages/service/src/plugin.ts, yarn.lock
Add 'import/no-default-export': 'error' and modify affected code
=> chore: Add 'import/no-default-export' lint rule

packages/utils/test/helpers.ts, packages/utils/test/test-service.ts
Removes the default export from utils
=> fix: remove default export from utils

.github/workflows/rehearsal-upgrade.yml
Staring work on rutting rehearsal on rehearsal (checking how action works)
=> [chore] Create rehearsal-upgrade.yml

packages/upgrade/src/transforms/2790/index.ts
=> refactor: simplify 2790-transfix

.github/workflows/rehearsal-upgrade.yml
=> Use Rehearsal's GitHub Action

packages/codefixes/src/codefix-collection.ts, packages/codefixes/src/codefixes.ts, packages/plugins/src/data/utils.ts, packages/plugins/src/plugins/diagnostic-fix.plugin.ts, packages/plugins/src/plugins/re-rehearse.plugin.ts
The master branch has linting errors that are propagating to other PRs.
=> chore: fixed linting errors

.github/workflows/test-and-lint.yml, .npmrc, package.json, packages/cli/package.json, packages/cli/src/utils.ts, packages/cli/test/helpers/utils.test.ts, packages/cli/test/test-helpers.ts, packages/migration-graph/tests/fixtures/scenarios.test.ts, packages/migration-graph/tests/fixtures/scenarios.ts, packages/migration-graph/tests/scenarios.test.ts, pnpm-lock.yaml
This PR changes the test and lint gh action and removes volta (for now) until volta adds support for pnpm.
=> fix: ghaction drop volta

packages/migration-graph/tests/fixtures/files.ts, packages/migration-graph/tests/fixtures/scenarios.test.ts, packages/migration-graph/tests/fixtures/scenarios.ts, packages/migration-graph/tests/migration-graph.test.ts, packages/migration-graph/tests/migration-strategy.test.ts
- This is in preparation for integrating service discovery to the graph.
=> test: add service to ember test fixtures

packages/migration-graph-ember/src/index.ts, packages/migration-graph-ember/src/utils/discover-ember-service-dependencies.ts, packages/migration-graph-ember/tests/utils/__snapshots__/ember.test.ts.snap, packages/migration-graph-ember/tests/utils/discover-ember-service-dependencies.test.ts
- Improve service discovery util.
- Add support for edge case for multiple import statements of `@ember/service` methods.
=> feat: improve service discovery util

packages/cli/src/utils.ts
=> feat: tighten default tsconfig

packages/migration-graph-ember/src/entities/ember-app-package-graph.ts, packages/migration-graph-ember/src/entities/ember-app-project-graph.ts, packages/migration-graph-shared/src/entities/package-graph.ts, packages/migration-graph-shared/src/entities/project-graph.ts
Usage of debug was incorrect. Fixed output string interpolation to use the correct tokens.
=> fix: debug output

packages/migration-graph-ember/src/entities/ember-app-project-graph.ts, packages/migration-graph-shared/src/entities/package.ts, packages/migration-graph-shared/src/entities/project-graph.ts, packages/migration-graph-shared/tests/entities/project-graph.test.ts, packages/migration-graph/src/migration-graph.ts, packages/migration-graph/tests/migration-graph.test.ts, packages/migration-graph/tests/migration-strategy.test.ts, packages/test-support/src/library.ts
This PR addresses Issue #514 first documented these concerns in Issue #439
=> feat(migration-graph): add support for workspaces for a js library

packages/codefixes/src/types.ts, packages/plugins/src/plugins/diagnostic-fix.plugin.ts, packages/reporter/src/types.ts, packages/upgrade/test/__snapshots__/upgrade.test.ts.snap
'insert' | 'delete' | 'replace' sounds more conventional than 'add' | 'delete' | 'replace'.
=> refactor: replace codeFixAction add with insert

packages/cli/src/commands/migrate.ts, packages/cli/src/commands/upgrade.ts, packages/cli/src/types.ts, packages/cli/test/commands/migrate.test.ts, packages/cli/test/commands/upgrade.test.ts
=> fix: fix format flags

packages/cli/src/commands/migrate.ts, packages/cli/test/commands/migrate.test.ts, packages/migrate/src/migrate.ts
Fixes #531
Before:
```
@rehearsal/migrate 0.0.39
✔ Initialization Completed! Running migration on @linkedin/ember-cli-pemberly-m3.
✔ Installing dependencies.
✔ Creating tsconfig.
info:    Migration started.
info:    Base path: /Users/chietala/Code/linkedin/ember-cli-pemberly-m3
info:    Moving /addon/-internal/api-compat.js to /addon/-internal/api-compat.ts
info:    Moving /addon/constants/request-header.js to /addon/constants/request-header.ts
info:    Moving /addon/utils/request-validation.js to /addon/utils/request-validation.ts
info:    Moving /addon/utils/schema.js to /addon/utils/schema.ts
info:    Moving /addon/utils/tunneled-request.js to /addon/utils/tunneled-request.ts
info:    Moving /addon/mixins/adapter-pemberly-m3.js to /addon/mixins/adapter-pemberly-m3.ts
info:    Moving …
```
=> fix: cleanup cli output

packages/codefixes/src/hints-codefix-collection.ts, packages/migrate/src/migrate.ts, packages/plugins/src/data/utils.ts, packages/plugins/src/plugins/diagnostic-fix.plugin.ts, packages/plugins/test/re-rehearse.plugin.test.ts, packages/reporter/src/index.ts, packages/reporter/src/normalize-paths.ts, packages/reporter/src/reporter.ts, packages/service/src/plugin.ts, packages/upgrade/src/upgrade.ts, packages/upgrade/test/transforms.test.ts, packages/upgrade/test/upgrade.test.ts
=> fix: use relative paths in report

packages/cli/src/commands/migrate.ts, packages/cli/src/commands/upgrade.ts, packages/cli/src/helpers/report.ts, packages/cli/src/types.ts, packages/cli/test/commands/migrate.test.ts, packages/cli/test/commands/upgrade.test.ts
=> fix: format extensions

packages/plugins/test/diagnostic-fix.plugin.test.ts, packages/plugins/test/utils.ts
Tests for https://github.com/rehearsal-js/rehearsal-js/pull/524
=> chore: test for 'diagnostic ordering' commit

package.json, pnpm-lock.yaml
- Remove unused babel types in root package.json
=> chore: removed usused dependencies

packages/migration-graph-shared/src/entities/package-graph.ts, packages/migration-graph-shared/src/entities/package.ts, packages/migration-graph-shared/tests/entities/package-graph.test.ts, packages/migration-graph-shared/tests/entities/project-graph.test.ts, packages/migration-graph/tests/migration-graph.test.ts, packages/migration-graph/tests/migration-strategy.test.ts, packages/test-support/src/library.ts, pnpm-lock.yaml
- Closes #532
- Simplify API for a plain js library in `test-support`.
=> feat: ignore css imports

packages/codefixes/package.json, packages/codefixes/src/typescript-codefix-collection.ts, packages/upgrade/test/__snapshots__/upgrade.test.ts.snap, pnpm-lock.yaml
This PR checks to see if prettier is installed and alters `FormatCodeOptions` accordingly. Doing so will insert code from CodeActions formatted code against these adjusted options.
=> feat: more correct formatting

packages/cli/package.json, packages/cli/src/commands/migrate/index.ts, packages/cli/src/commands/migrate/tasks/config-lint.ts, packages/cli/src/commands/migrate/tasks/config-ts.ts, packages/cli/src/commands/migrate/tasks/convert.ts, packages/cli/src/commands/migrate/tasks/create-scripts.ts, packages/cli/src/commands/migrate/tasks/dependency-install.ts, packages/cli/src/commands/migrate/tasks/initialize.ts, packages/cli/test/commands/migrate.test.ts, packages/migrate/package.json, packages/migrate/src/migrate.ts, packages/migrate/test/index.test.ts, pnpm-lock.yaml
This PR fixes bugs related to promises not being handled from Listr. We can now properly render the running tasks within the Listr stream and no longer clobber.
=> fix: migrate cmd handle listr async tasks

packages/cli/src/commands/migrate/tasks/convert.ts, packages/cli/src/helpers/report.ts, packages/cli/src/types.ts, packages/cli/src/utils.ts, packages/cli/test/helpers/utils.test.ts
For the launch editor issue in the comment of #570.
Also added the summary message in interactive mode when migration completes:
=> fix: launch editor issue && show summary message in interactive mode

packages/cli/src/helpers/report.ts, packages/plugins/src/plugins/diagnostic-fix.plugin.ts, packages/plugins/src/plugins/lint-check.plugin.ts, packages/reporter/src/reporter.ts, packages/reporter/src/types.ts, packages/reporter/test/__snapshots__/reporter.test.ts.snap, packages/reporter/test/fixtures/reporter/rehearsal-report.json, packages/reporter/test/fixtures/sarif-formatter/add-artifact.ts, packages/reporter/test/fixtures/sarif-formatter/add-result.ts, packages/reporter/test/fixtures/sarif-formatter/add-rule.ts, packages/reporter/test/fixtures/sarif-formatter/initial-data.ts, packages/upgrade/test/__snapshots__/upgrade.test.ts.snap
Closes #598 
Add number of fixed errors in report, revise cli output message
=> refactor: add error count in report

packages/cli/src/commands/migrate/tasks/dependency-install.ts, packages/cli/test/commands/migrate.test.ts
=> feat: install @types/node

packages/cli/test/commands/__snapshots__/migrate.test.ts.snap, packages/cli/test/commands/migrate.test.ts
The test checks the rehearsal version and has to be updated every release. 
This PR should fix this
=> fix: Correct peerDependencies typescript version

package.json, release.js
=> fix: release script

packages/cli/src/commands/migrate/tasks/config-lint.ts, packages/cli/test/commands/upgrade.test.ts
This PR fixes #631 and addresses a small bug in an upgrade cli test
=> fix: cli find eslint

packages/cli/src/helpers/report.ts
=> fix: print sonarqube report

packages/cli/test/commands/migrate/__snapshots__/convert.test.ts.snap, packages/cli/test/commands/migrate/convert.test.ts, packages/cli/test/commands/migrate/initialize.test.ts, packages/cli/test/test-helpers/index.ts
This fixes #715.
Instead of hard coded waiting time, the code now creates a readable stream and check the current message from console, and sends keycode based on different types of prompts.
With this new mechanism, it would ensure we are sending the correct keys at the correct time, and cut all of the unnecessary wait time.
=> fix: flakiness in interactive mode test

packages/utils/src/cli.ts, packages/utils/test/cli.test.ts
=> fix: guard executable with volta when installing deps

package.json, pnpm-lock.yaml
Update deps to latest available
=> chore: deps

packages/cli/test/commands/migrate/__snapshots__/e2e.test.ts.snap, packages/cli/test/commands/upgrade.test.ts
=> fix: upgrade cli tests

release.js
=> fix: push only new tag during release

packages/cli/src/commands/migrate/index.ts, packages/cli/src/commands/migrate/tasks/initialize.ts, packages/cli/test/commands/migrate/__snapshots__/e2e.test.ts.snap, packages/cli/test/commands/migrate/__snapshots__/initialize.test.ts.snap, packages/cli/test/commands/migrate/e2e.test.ts, packages/cli/test/commands/migrate/initialize.test.ts, packages/cli/test/test-helpers/index.ts, packages/utils/src/cli.ts
Detect default user config `rehearsal-config.json` without `--userConfig`.
This PR fixes #684 and #737.
=> feat: default user config

.npmrc
update .npmrc to be consistent with pinned node version.
=> chore: update use-node-version

packages/codefixes/src/fixes/addMissingTypesBasedOnInheritance/index.ts
=> chore: types based on inheritance tune up

packages/migration-graph-ember/src/entities/ember-addon-package.ts
No longer necessary in this file.
=> fix: remove no-explicity-any

README.md, packages/cli/src/commands/migrate/index.ts
=> chore: add migrate-by-directory in md

CHANGELOG.md, package.json, release.js
Fix issues with a changelog generation
=> fix: fix versioning

packages/cli/src/commands/migrate/tasks/config-lint.ts
=> feat: include .cjs eslint config ext

packages/cli/test/commands/migrate/__snapshots__/e2e.test.ts.snap, packages/cli/test/commands/migrate/e2e.test.ts, packages/cli/test/commands/migrate/regen.test.ts, packages/regen/src/regen.ts
Clean up some tests:
- Remove git related tests
- Remove one unnecessary error message in regen
=> test: clean up tests

packages/migration-graph-ember/src/entities/ember-app-project-graph.ts, packages/migration-graph-ember/test/entities/ember-app-project-graph.test.ts
This fixes #825. 
For more details about root cause and the solution please read the related issue.
=> fix(migration-graph): discover package when passed an entrypoint

packages/cli/package.json, packages/cli/src/commands/migrate/init-command.ts, packages/cli/test/commands/migrate/__snapshots__/init-command.ember-addon.test.ts.snap, packages/cli/test/commands/migrate/__snapshots__/init-command.ember-app.test.ts.snap, packages/cli/test/commands/migrate/__snapshots__/init-command.test.ts.snap, packages/cli/test/commands/migrate/init-command.ember-addon.test.ts, packages/cli/test/commands/migrate/init-command.ember-app.test.ts, packages/cli/test/commands/migrate/init-command.test.ts, packages/cli/test/test-helpers/init-command-test-utils.ts, pnpm-lock.yaml
Adding ember scenario tests for `migrate init`.
=> chore: add ember tests for migrate init

packages/migrate/test/__snapshots__/migrate.test.ts.snap, packages/migrate/test/fixtures/project/tsconfig.json, packages/migrate/test/migrate.test.ts
Fixes master branch. #856 was merged with existing failures. This fixes the failing tests by regenerating the snapshots and adding the correct config in the tsconfig.json.
=> chore: fix master

packages/cli/test/commands/migrate/__snapshots__/config-lint.ember-app.test.ts.snap, packages/cli/test/commands/migrate/__snapshots__/init-command.ember-app.test.ts.snap, packages/cli/test/commands/migrate/init-command.ember-app.test.ts, packages/test-support/package.json, packages/test-support/src/project.ts, packages/test-support/src/scenarios.ts, pnpm-lock.yaml
Enable ember 4 for ember app testing.
=> test: enable ember4 for ember app

packages/ts-utils/src/helpers/typescript-ast.ts
In the original function, we visited each tree node until finding the target.
In the updated function we visit children nodes only if the target is inside the current node, otherwise, just skip the current node.
See console: https://astexplorer.net/#/gist/798704890e6a18e04c7d7ed9f2009ffc/20a1cb1cfb8dd90acd0f305efa88610f98a597e8
=> chore: improve performance of AST node searching

packages/codefixes/src/hints-provider.ts, packages/migrate/src/glint-utils.ts, packages/migrate/test/fixtures/project/.eslintrc.json, packages/migrate/test/fixtures/project/.prettierrc, packages/migrate/test/fixtures/project/package-lock.json, packages/migrate/test/fixtures/project/package.json, packages/migrate/test/migrate.test.ts, packages/plugins/src/plugins/glint-fix.plugin.ts, packages/plugins/src/plugins/glint-report.plugin.ts, packages/plugins/src/plugins/lint.plugin.ts, packages/upgrade/test/__snapshots__/upgrade.test.ts.snap
Hooks glint plugins into the Rehearsal reporting system.
=> feat: add glint plugin fixes to reporter

packages/plugins/src/plugins/lint.plugin.ts
=> fix: check report before accessing prop

README.md
Update `README.md` with devDependency install guidance.
=> chore: update README.md with devDep install

packages/migrate/src/migrate.ts, packages/migrate/test/fixtures/project/.rehearsal/services-map.json, packages/migrate/test/fixtures/project/src/with-mapped-service.gjs, packages/migrate/test/fixtures/project/src/with-mapped-service.js, packages/migrate/test/fixtures/project/types.d.ts, packages/migrate/test/migrate.test.ts, packages/plugins/src/plugins/transform.plugin.ts
Covers non-qualified service injection. 
The solution is using provided `services-map.json` file to include services by their names.
=> feat: non-qualified service injection, based on provide map file

.github/workflows/get-diagnostics.yml
This fixes the workflow that has been failing since https://github.com/rehearsal-js/rehearsal-js/pull/965 was introduced.
=> fix: get diagnostics workflow

package.json, pnpm-lock.yaml
Changelog has not been updated last few tags due to missing dependency.
=> chore: add missing changelog-cli package

README.md, packages/cli/src/commands/fix/command.ts, packages/cli/src/commands/graph/command.ts, packages/cli/src/commands/move/command.ts
FIx few typos across CLI helps and Readme
=> chore: fix typos

packages/cli/src/commands/move/tasks/mv.ts, packages/cli/src/commands/move/tasks/mvWorker.ts
Fixes #1031 
This PR:
refactors the moveTask into a worker
=> refactor(cli): git task into worker

packages/codefixes/test/__snapshots__/base-codefixes.test.ts.snap, packages/codefixes/test/fixtures/base-codefixes/annotateWithStrictTypeFromJSDoc/index.ts, packages/ts-utils/src/helpers/typescript-ast.ts
Fixes: #1060 
Validated locally.
=> fix: catch and return false if getTypeFromTypeNode fails

README.md, packages/cli/src/commands/graph/command.ts
We simplified the public api in #1053. Updating the docs to reflect that.
=> docs: update docs

packages/cli/src/commands/fix/command.ts
This adds JS globs to ignore for fixes
=> fix: only have ts files in fix

packages/plugins/src/plugins/glint-fix.plugin.ts, packages/smoke-test/test/commands/__snapshots__/fix.test.ts.snap
We seem to be not be captureing the count of things that glint is fixing.
=> fix: increment reporter for glint

packages/plugins/src/plugins/diagnostic-report.plugin.ts, packages/plugins/src/plugins/glint-report.plugin.ts
While fixing typos for `r/supresssed/suppressed` I found some more in another package.
=> chore(plugins): fix typos for word suppressed

packages/migrate/test/__snapshots__/migrate.test.ts.snap, packages/migrate/test/fixtures/project-basic/.eslintrc.json, packages/migrate/test/fixtures/project-basic/.prettierrc, packages/migrate/test/fixtures/project-basic/.template-lintrc.js, packages/migrate/test/fixtures/project-basic/package-lock.json, packages/migrate/test/fixtures/project-basic/package.json, packages/migrate/test/fixtures/project-basic/src/foo.ts, packages/migrate/test/fixtures/project-basic/tsconfig.json, packages/migrate/test/fixtures/project/src/foo.ts, packages/migrate/test/migrate.test.ts, packages/plugins/src/plugins/diagnostic-fix.plugin.ts, packages/plugins/src/plugins/glint-fix.plugin.ts
Fixes missing exit criteria for drain mode in glint.fix plugin and fixes diagnotic.fix plugin. 
Fixes: https://github.com/rehearsal-js/rehearsal-js/issues/1077
=> fix: drain mode exit criteria 
