rehearsal-js/rehearsal-js

- package.json
- packages/cli/package.json
- packages/cli/src/commands/ts.ts
- packages/cli/src/ts-migrate.ts
- packages/cli/test/commands/ts.test.ts
- packages/cli/test/fixtures/app_with_comments/foo.ts
- packages/plugin-ts-migrate/package.json
- yarn.lock
Configure Rehearsal ts-migrate flow instead of running ts-migrate cli.
This gives us more control over ts-migrate plugin configs:
- have full error messages after running tsIgnorePlugin
- run eslintFixPlugin plugin after pluginTSMigrateAutofix
We can, probably, even merge tsIgnorePlugin and pluginTSMigrateAutofix into a single plugin in future.
> Update Rehearsal's tsMigrate workflow

- .gitignore
- packages/migration/src/migrate.ts
- packages/migration/src/plugins/diagnostics-autofix.plugin.ts
- packages/migration/src/reporter/formatters/json.ts
- packages/migration/src/reporter/formatters/pull-request-md.ts
- packages/migration/src/reporter/reporter.ts
- packages/migration/src/reporter/types.ts
- packages/migration/test/fixtures/migrate/.rehearsal-report.output.json
- packages/migration/test/fixtures/migrate/.rehearsal-report.output.md
- packages/migration/test/migrate.test.ts
Add reporter to the `migrate` command.
Reporter keeps all items in memory and allows to print reports in different formats.
Currently has plain json output and md format for PR (see tests).
Will be migrated to @rehearsal/reporter in one of the following PRs
> refactor: integrate reporter to the migrate function

- packages/cli/src/commands/ts.ts
- packages/migrate/src/migrate.ts
- packages/migrate/test/migrate.test.ts
CLI saves a report in specified format. 
Migrate is not responsible for saving report in any format, just to fill it up.
> fix: clean up the second report generation logic

- packages/migrate/src/migrate.ts
Function parseJsonConfigFileContent expects basePath [to be a location of the tscongfig.json](https://github.com/microsoft/TypeScript/issues/5276#issuecomment-148786708).
> fix: provide a correct basePath for parsing tsconfig.json content

- .eslintrc.js
- packages/migrate/src/helpers/transform-utils.ts
- packages/migrate/src/helpers/typescript-ast.ts
- packages/migrate/src/interfaces/fix-transform.ts
- packages/migrate/src/plugins/diagnostics-autofix.plugin.ts
- packages/migrate/src/rehearsal-service.ts
- packages/migrate/src/transforms/2790-fix-transform.ts
- packages/migrate/test/fixtures/migrate/.rehearsal-report.output.json
- packages/migrate/test/fixtures/migrate/.rehearsal-report.output.md
- packages/migrate/test/fixtures/migrate/2790-import-1.ts.input
- packages/migrate/test/fixtures/migrate/2790-import-1.ts.output
- packages/migrate/test/fixtures/migrate/2790-import-2.ts.input
- packages/migrate/test/fixtures/migrate/2790-import-2.ts.output
- packages/migrate/test/fixtures/migrate/2790.ts.input
- packages/migrate/test/fixtures/migrate/2790.ts.output
- packages/migrate/test/migrate.test.ts
Error 2790 is the error we receive when we delete a property on a type or class that's required. The auto fix adopted in this PR is to make the property optional in the type definition or class definition. This PR handles when the type or class is local to the file where the error happens, or when the type or class is imported from a different file.
> feat: Fix typescript error 2790 [PPTF-4317]

- packages/cli/src/helpers/report.ts
- packages/cli/test/commands/ts.test.ts
Count how many times error was detected:
```
"uniqueErrors": 2,
"totalErrors": 20,
"totalErrorsList": {
"1016": 15,
"1192": 5
} ,
"fixedErrors": 5,
"fixedErrorsList": {
"1016": 5,
"1192": 0
} ,
```
> refactor: Add counter of errors tp the report

- package.json
- packages/cli/package.json
- packages/cli/test/commands/ts.test.ts
- packages/diagnostic/package.json
- packages/diagnostic/test/fixtures/diagnose/.rehearsal-diagnostics-only.json.output
- packages/diagnostic/test/fixtures/diagnose/.rehearsal-diagnostics.json.output
- packages/diagnostic/test/fixtures/diagnose/first.ts.output
- packages/migrate/package.json
- packages/migrate/test/fixtures/migrate/.rehearsal-report.output.md
- packages/reporter/package.json
- packages/tsc-transforms/package.json
- yarn.lock
Chore PR which bumps typescript dev-dep to latest. This PR explicitly imports typescript in the root package as this fix's an issue with the wrong version of the typescript compiler being used in packages with peerDependencies on typescript.
> chore(deps-dev): bump typescript to latest minor

- packages/migrate/src/helpers/transform-utils.ts
- packages/migrate/src/plugins/diagnostics-autofix.plugin.ts
- packages/migrate/src/transforms/2345-fix-transform.ts
- packages/migrate/src/transforms/index.ts
- packages/migrate/test/fixtures/migrate/.rehearsal-report.output.json
- packages/migrate/test/fixtures/migrate/.rehearsal-report.output.md
- packages/migrate/test/fixtures/migrate/2345.ts.input
- packages/migrate/test/fixtures/migrate/2345.ts.output
This PR is to address the following error from nuage-core.
`src/components/FeedbackDialog/index.tsx:234:22 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'SetStateAction'.
234 setJiraError(error);
~~~~~`
> feat: add details hint to TS2345

- packages/cli/package.json
- packages/diagnostic/package.json
- packages/migrate/package.json
- packages/reporter/package.json
- packages/tsc-transforms/package.json
This PR enables eslint autofix. By running 'yarn lint', autofixable lint errors will be fixed, saving devs the time to manually reformatting the code.
> Chore: enable lint autofix

- packages/migrate/src/rehearsal-service.ts
- packages/migrate/test/fixtures/migrate/tsconfig.json
During the applying a hack I found a, probably, proper solution for the compilation of global types.
These functions are optional by default, but they are used to find typeRoots in the TypeScript compiler.
> Fix compilation process to include all modules

- packages/migrate/src/interfaces/fix-transform.ts
- packages/migrate/src/migrate.ts
- packages/migrate/src/plugins/diagnostics-autofix.plugin.ts
- packages/migrate/src/plugins/empty-lines-preserve.plugin.ts
- packages/migrate/src/plugins/empty-lines-restore.plugin.ts
- packages/migrate/src/plugins/lint.plugin.ts
- packages/migrate/src/transforms/2345-fix-transform.ts
- packages/migrate/src/transforms/2571-fix-transform.ts
- packages/migrate/src/transforms/2790-fix-transform.ts
- packages/migrate/src/transforms/4082-fix-transform.ts
- packages/migrate/src/transforms/6133-fix-transform.ts
- packages/service/README.md
- packages/service/package.json
- packages/service/src/index.ts
- packages/service/src/plugin.ts
- packages/service/src/rehearsal-service-host.ts
- packages/service/src/rehearsal-service.ts
- packages/service/test/fixtures/dummy.ts
- packages/service/test/rehearsal-service.test.ts
- packages/service/test/tsconfig.json
- packages/service/tsconfig.json
Make service available to use outside of migrate.
Will make Service to be responsible of running plugins later.
> chore: Move Rehearsal Service out of @rehearsal/migrate

- packages/migrate/test/migrate.test.ts
- packages/reporter/src/formatters/json-formatter.ts
- packages/reporter/src/formatters/md-formatter.ts
- packages/reporter/src/index.ts
- packages/reporter/src/reporter.ts
- packages/reporter/test/reporter.test.ts
Remove default export
Rename pullRequestMd to mdFormatter, because it just an example of md formatter (not specifically for PRs)
> chore: Refactor Reporter: better naming and no default exports

- packages/cli/src/helpers/report.ts
- packages/reporter/src/formatters/md-formatter.ts
- packages/reporter/src/reporter.ts
- packages/reporter/src/types.ts
- packages/reporter/test/fixtures/.rehearsal-report.input.json
- packages/reporter/test/fixtures/.rehearsal-report.output.json
- packages/reporter/test/reporter.test.ts
- packages/upgrade/src/helpers/transform-utils.ts
- packages/upgrade/src/interfaces/fix-transform.ts
- packages/upgrade/src/plugins/diagnostics-autofix.plugin.ts
- packages/upgrade/src/transforms/2322-fix-transform.ts
- packages/upgrade/src/transforms/2345-fix-transform.ts
- packages/upgrade/src/transforms/2571-fix-transform.ts
- packages/upgrade/src/transforms/2790-fix-transform.ts
- packages/upgrade/src/transforms/4082-fix-transform.ts
- packages/upgrade/src/transforms/6133-fix-transform.ts
- packages/upgrade/test/fixtures/upgrade/.rehearsal-report.output.json
- packages/upgrade/test/upgrade.test.ts
This PR changes the report to include more transform data that will be used for the sarif file. 
1. Return type of the transform function changes from `FixedFile[]` to `FixResult.` The former only includes the name and content of source files that have been modified, while the latter includes an array of source files that have been modified and an array of source file to which only comments have been added, and locations in these source files where codemods are made or comments are added.
2. For readability, in the ReportItem type, `file` field is changed to `analysisTarget` to differentiate it from `fixedFiles` and `commentedFiles`, borrowing a term from sarif. `location` is changed to `nodeLocation`, as `nodeKind` or `nodeText`, to be differentiated from `location` in `fixedFiles` and …
> refactor: expose more transform data for sarif reporting

- package.json
It was [recently removed](https://github.com/rehearsal-js/rehearsal-js/pull/270/files#diff-6e2e2a1851648938b325ba84de634407a4e69a644ea61102df15ca4a8a7a9758L95), but we need this to run the hook
> chore: Return pre-commit dependency

- package.json
- packages/cli/package.json
- packages/migrate/package.json
- packages/plugins/package.json
- packages/reporter/package.json
- packages/service/package.json
- packages/upgrade/package.json
- packages/utils/package.json
- bumps node to lts
- leverages volta extends so we only need to manage node/yarn versions once
- bumps min node version engine from 10 to 14
> chore: node lts and volta extends

- packages/cli/src/helpers/report.ts
- packages/cli/test/commands/upgrade.test.ts
- packages/migrate/src/plugins/discover-types.plugin.ts
- packages/plugins/package.json
- packages/plugins/src/data/index.ts
- packages/plugins/src/data/utils.ts
- packages/plugins/src/fix-transform/index.ts
- packages/plugins/src/fix-transform/interfaces.ts
- packages/plugins/src/fix-transform/utils.ts
- packages/plugins/src/index.ts
- packages/reporter/package.json
- packages/reporter/src/formatters/md-formatter.ts
- packages/reporter/src/formatters/sarif-formatter.ts
- packages/reporter/src/index.ts
- packages/reporter/src/reporter.ts
- packages/reporter/src/types.ts
- packages/upgrade/package.json
- packages/upgrade/src/plugins/diagnostics-autofix.plugin.ts
- packages/upgrade/src/transforms/2571/index.ts
- packages/upgrade/src/transforms/2790/index.ts
- packages/upgrade/src/transforms/4082/index.ts
- packages/upgrade/src/transforms/6133/index.ts
- packages/upgrade/test/fixtures/upgrade/.rehearsal-report.output.json
- packages/upgrade/test/fixtures/upgrade/.rehearsal-report.output.sarif
- packages/upgrade/test/upgrade.test.ts
- yarn.lock
Adds sarif-formatter in @rehearsal/reporter; Adds transform data collection in @rehearsal/upgrade transforms; Add data messaging in @rehearsal/plugins. 
See attached file for sample sarif file generated locally.
Next iteration will be to fully utilize the built-in properties as shown in the sarif viewer, such as 'suppressed', 'unchanged', 'updated'.
> feat: add sarif-formatter

- packages/reporter/src/formatters/sarif-formatter.ts
- packages/reporter/src/reporter.ts
- packages/upgrade/test/fixtures/upgrade/.rehearsal-report.output.sarif
- packages/upgrade/test/upgrade.test.ts
Adds a few properties for the sarif viewer:
`baselineState`, `kind`, `relatedLocations`, for `result` and `automationDetails` for `run`, `index` for `artifactLocation`.
> refactor: add properties for sarif viewer

- packages/reporter/src/formatters/sarif-formatter.ts
This refactors the sarif formatter to not rely on module scope state. In general we want to avoid manually GCing objects by constructing code in a way where once the objects out out of scope the GC will take care of the objects for us.
> chore: refactor sarif formatter

- packages/cli/bin/rehearsal.js
- packages/cli/src/commands/migrate.ts
- packages/cli/src/commands/upgrade.ts
- packages/cli/src/index.ts
- packages/cli/test/runner.ts
- packages/cli/test/test-helpers.ts
I'm trying to `import { rehearsal } from "@rehearsal/cli"` in GitHub Action, but it runs because of `parse(...)` in `index.js`.
Let's keep calling `parse(...)` in `./bin` and make is possible to import commands and tun them in different scenarios (including test can be upgraded).
> chore: Avoid running CLI in index.ts file, only in ./bin

- packages/plugins/test/__snapshots__/empty-lines-restore.plugin.test.ts.snap
- packages/plugins/test/empty-lines-preserve.plugin.test.ts
- packages/plugins/test/empty-lines-restore.plugin.test.ts
- packages/plugins/test/fixtures/empty-lines-preserve.fixture
- packages/plugins/test/fixtures/empty-lines-restore.fixture
- packages/plugins/test/fixtures/re-rehearse.fixture
- packages/plugins/test/re-rehearse.plugin.test.ts
This brings back fixture input files to make sure we can control the whitespace of the input. We still should retain the snapshots because they will fail if we mess up the whitespace and its easy to update if the change is intentional.
> bring back fixture files

- packages/cli/src/commands/upgrade.ts
Planning to remove all git interaction, but let's just keep them disabled with --dry_run for now.
> chore: Don't create a branch when run with --dry_run

- packages/cli/src/commands/migrate.ts
- packages/cli/src/commands/upgrade.ts
- packages/cli/src/types.ts
- packages/cli/src/userConfig.ts
- packages/cli/test/commands/upgrade.test.ts
Removed redundant options (-a doesn't currently work as expected)
Fix some typo, rename types to start from upper case letters
> chore: Remove -a and -i options from upgrade command + typo

- packages/cli/test/commands/migrate.test.ts
- packages/cli/test/commands/upgrade.test.ts
- packages/cli/test/test-helpers.ts
It's not necessary and clean to do `yarn link` to get executable on the machine for test in `migrate`, this PR adds a helper function to run the bin directly from `./bin/rehearsal.js`
> Remove linking in test

- .gitignore
- packages/cli/src/commands/migrate.ts
- packages/cli/src/commands/upgrade.ts
- packages/cli/src/helpers/report.ts
- packages/cli/src/types.ts
- packages/cli/src/utils.ts
- packages/cli/test/commands/migrate.test.ts
- packages/cli/test/commands/upgrade.test.ts
- packages/reporter/src/index.ts
- packages/reporter/src/reporter.ts
- packages/reporter/src/types.ts
- yarn.lock
Add report option to upgrade command similar to migrate [needed for GitHub Action]
Optimize some of upgrade command args
Fix some typos
Rename reports to `report.***` and moved them to `.rehearsal` directory
Experimenting with using argument for basePath, means command has to be run as `rehearsal upgrade [basePath]` without -s
> refactor: Upgrade command report config and options optimization

- packages/cli/src/commands/migrate.ts
During migration if a JS file has no dependency, it won't be added into the migration file list. This PR adds the detection for files with no dependency, to include them into the migration file list.
> chore: handle file with no dependency

- packages/codefixes/package.json
- packages/migrate/package.json
- packages/migration-graph-ember/package.json
- packages/migration-graph-shared/package.json
- packages/migration-graph/package.json
- packages/service/package.json
- packages/upgrade/package.json
- packages/utils/package.json
Closes #305. We can try even 3.x (but we need to test r, but I think 4.0 is fine for now.
> chore: Reduce peerDependencies TS version to 4.0

- .vscode/launch.json
- vitest.config.ts
This PR adds a vitest.config.ts to the project root for vscode and fixes launch.json type to `node`
> test: add vitest config for vscode

- .github/workflows/test-and-lint.yml
- lerna.json
- package.json
- packages/migration-graph-ember/package.json
- pnpm-lock.yaml
- tsconfig.json
Fixes #408. On publish the tgz package now properly contains workspace package versions
```
// rehearsal-cli-0.0.37.tgz/package.json
"dependencies": {
"@microsoft/api-documenter": "^7.13.68",
"@rehearsal/migrate": "0.0.37",
"@rehearsal/migration-graph": "0.0.37",
"@rehearsal/reporter": "0.0.37",
"@rehearsal/upgrade": "0.0.37",
```
> fix: remove lerna

- packages/migration-graph-ember/src/utils/ember.ts
- packages/migration-graph-ember/tests/fixtures/package-fixtures.ts
- packages/migration-graph-ember/tests/utils/__snapshots__/ember.test.ts.snap
- packages/migration-graph-ember/tests/utils/ember.test.ts
- Wrote a test.
- Bad assumption previously that an app would have a `ember` field in package.json.
> feat: ember app detect

- .eslintrc.js
This PR turns off 2 eslint plugins because they are taking forever to run:
- import/named
- import/namespace
> test: reduce eslint import rules

- packages/cli/src/commands/migrate.ts
- packages/cli/src/helpers/state.ts
- packages/cli/src/types.ts
- packages/cli/test/helpers/__snapshots__/state.test.ts.snap
- packages/cli/test/helpers/state.test.ts
This PR adds migration state to keep track of the progress of migration in interactive mode, including:
1. Create a state file `.rehearsal/migration-state.json` and `git add` it
2. Every time when running `rehearsal migration`, it would load the previous state if there is any, verify and update the state if needed.
- Make sure migration status in state file matches what we have on disk
- Update ts-ignore count for each migrated file
4. There are 3 cases when showing the migration progress/state in interactive mode:
- package has not started any migration before -> show "no progress found"
- package had a migration with remaining JS files ->  show "x/x migrated, x rehearsal todos"
- fully migrated with no JS and rehearsal todo -> show "completed" and disable this option
5. We had …
> feat: migration state

- packages/cli/src/utils.ts
When running `yarn tsc` with `yarn@3`, it would error out since there is no `--ignore-scripts` option anymore.
```
✖ Command failed with exit code 1: yarn add -D typescript --ignore-scripts
Unknown Syntax Error: Command not found; did you mean one of:
0. yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode…
1. yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode…
While running add -D typescript --ignore-scripts
```
This PR detects if it's on `yarn@3` and remove `--ignore-scripts` for this case.
> fix: don't use --ignore-scripts option with yarn@3

- packages/migration-graph-ember/package.json
- packages/migration-graph/package.json
- pnpm-lock.yaml
- `migration-graph` The package has been hollowed out to migration-graph-shared and migration-graph-ember. These deps are no longer used.
- `migration-graph-ember` replace version with workspace:* for `migration-graph-shared` dep.
> chore: remove unused dependencies in migration-graph

- packages/cli/src/commands/migrate.ts
- packages/cli/src/commands/upgrade.ts
- packages/cli/test/commands/migrate.test.ts
- packages/migrate/tests/index.test.ts
- packages/reporter/src/formatters/sarif-formatter.ts
- packages/reporter/src/reporter.ts
- packages/reporter/src/types.ts
- packages/reporter/test/__snapshots__/reporter.test.ts.snap
- packages/reporter/test/__snapshots__/sarif-formatter.test.ts.snap
- packages/reporter/test/fixtures/reporter/rehearsal-report.json
- packages/reporter/test/fixtures/sarif-formatter/add-artifact.ts
- packages/reporter/test/fixtures/sarif-formatter/add-result.ts
- packages/reporter/test/fixtures/sarif-formatter/add-rule.ts
- packages/reporter/test/fixtures/sarif-formatter/initial-data.ts
- packages/reporter/test/reporter.test.ts
- packages/upgrade/test/upgrade.test.ts
This PR address various UX bugs:
- removes redundant tsc check post cli/migrate migration
- adds sonarqube formatter to upgrade/migrate cli
- defaults sarif formatter for upgrade/migrate cli
- implements a ReporterMeta, cleans params
- fixes hardcoded values in reporter with tsc version and command name
- defaults adding @latest tsc with migrate cli for all instances
- defaults tsconfig strict to true with migrate cli when tsconfig exists
> refactor: ux improvements

- packages/cli/src/utils.ts
Fixes a bug where yarn classic will return the `binaryName` with the path. Implementation now covers both.
> fix: yarn classic binary path

- packages/migration-graph-ember/src/entities/ember-app-project-graph.ts
- packages/migration-graph-ember/tests/entities/ember-addon-package-graph.test.ts
- packages/migration-graph-ember/tests/entities/ember-app-package-graph.test.ts
- packages/migration-graph-ember/tests/entities/ember-app-project-graph.test.ts
- packages/migration-graph-shared/src/graph/graph.ts
- packages/migration-graph-shared/tests/graph/graph.test.ts
- packages/migration-graph/src/migration-strategy.ts
- packages/migration-graph/tests/migration-graph.test.ts
A couple of issues were fixed:
*`graph.topSort(...)` now takes an optional argument for a `rootNode`*
This will allow for get the order of an app's migration relative to a given package, specifically fixing a bug where I thought the order was in root to leaf and reversing it. It actually was a bug because I was always printing from the first added package of the graph.
*backfill services when an org is used on packageName that doesn't match moduleName*
- In some cases an ember-addon may have a moduleName that differs from packageJson.name
- This is a problem in the project-graph because we use the packageName as a key.
- Now we store multiple lookup entries in the graph registry so `some-addon` and `@some-org/some-addon` will map to the same package.
> fix: graph edge cases

- packages/migration-graph-ember/src/entities/ember-app-package-graph.ts
- packages/migration-graph-ember/src/entities/ember-app-project-graph.ts
- packages/migration-graph-ember/src/mappings-container.ts
- packages/migration-graph/src/migration-graph.ts
- packages/migration-graph/src/util/printer.ts
**Summary**
Root caused performance bug in rehearsal/migration-graph when running against our large internal ember app. 
This issue was “fixed” was #450, how opened back up in #470.
**Details**
When we create a graph for an ember app, we `fastglob` all package.json’s from the directory first, then packages entities to the graph `EmberAppProjectGraph.addPackageToGraph()`.
This is sufficient enough to find all nodes.
Now we have to create edges.
After we add a package to the graph, we follow-up with looking at it's dep and devDeps and inner joining that data the manifest of in-repo addons defined in the project root `package.json`.  This method was renamed from ~EmberAppProjectGraph.buildAnalyzedPackageTree~  to`EmberAppProjectGraph.discoverEdgesFromDependencies()`.
Previously, there was …
> fix: perf when crawling deps

- package.json
- packages/migration-graph-ember/package.json
- packages/test-support/fixtures/test-ignore-node-modules/package.json
- pnpm-lock.yaml
This completes issue #365. In a previous PR I removed all unused babel code, these dependencies were left behind.
> chore: remove unused babel dependencies

- packages/cli/src/commands/migrate.ts
- packages/cli/src/commands/upgrade.ts
For [#484 ](https://github.com/rehearsal-js/rehearsal-js/issues/484)
1. Displays version at the start of either migrate or upgrade.
2. Displays version for "rehearsal --version"/"rehearsal -V".
3. Displays version for"rehearsal migrate --version"/"rehearsal migrate -V".
4. Displays version for "rehearsal upgrade --version"/ "rehearsal upgrade -V".
> fix: display version for migrate and upgrade

- packages/cli/src/commands/migrate.ts
For #481: update `exitOnError` to `true` in `rehearsal migrate`, in order to hard stop the CLI if there is any issue. The reason we had it on `false` was that we don't want to quit the CLI if there we got non 0 exit during `tsc` check.
> fix: migrate cli should stop on failure

- package.json
- packages/cli/src/commands/migrate.ts
- packages/cli/src/helpers/state.ts
- packages/codefixes/src/2322/fixtures/2322.ts.output
- packages/codefixes/src/2345/fixtures/2345.ts.output
- packages/codefixes/src/2571/fixtures/2571.ts.output
- packages/codefixes/src/hints-codefix-collection.ts
- packages/plugins/src/plugins/diagnostic-fix.plugin.ts
- packages/upgrade/src/upgrade.ts
- packages/upgrade/test/fixtures/upgrade/react-processed.tsx.input
- packages/upgrade/test/fixtures/upgrade/react-processed.tsx.output
- packages/upgrade/test/fixtures/upgrade/react.tsx.output
- packages/upgrade/test/fixtures/upgrade/ts-errors.ts.output
- packages/upgrade/test/fixtures/upgrade/ts-multiline-hint.ts.output
- packages/upgrade/test/fixtures/upgrade/ts-processed.ts.input
- packages/upgrade/test/fixtures/upgrade/ts-types.ts.input
- packages/upgrade/test/fixtures/upgrade/ts-types.ts.output
Closes #495 
This PR can optionally be merged; however I would recommend we move away from @ts-ignore. The API for @ts-ignore and @ts-expect-error are nearly identical. A key delta for @ts-expect-error, in that the compiler will throw if Rehearsal has inlined a TODO when there isn't actually a compiler error. This is super helpful for when folks are cleaning up Rehearsal TODO's and forget to delete the Rehearsal comment after fixing the error.
> refactor: replace @ts-ignore with @ts-expect-error

- packages/cli/src/commands/migrate.ts
- packages/cli/src/helpers/state.ts
- packages/cli/src/utils.ts
- packages/cli/test/commands/migrate.test.ts
For #480.
This issue should be fixed by https://github.com/rehearsal-js/rehearsal-js/pull/501, since the CLI would exit on error during installation and would not continue to do the conversion. However, I brought `exitOnError: false` in again from https://github.com/rehearsal-js/rehearsal-js/pull/502 by accident.
This PR:
- Set `exitOnError` back to `true`
- Add a check for uncommitted files before proceeding
- Reset all files changed by the CLI to the previous state if there is any error
> fix: reset files when cli falis

- packages/reporter/src/formatters/sarif-formatter.ts
- packages/reporter/test/__snapshots__/sarif-formatter.test.ts.snap
[#496](https://github.com/rehearsal-js/rehearsal-js/issues/496) 
Tried using the Fixes property of sarif, but Fixes won't show in sarif reader. So I am sticking to property bag, which is more straightforward. 
Please refer to the attachments for "after" and "before" screenshots.
> fix: remove sarif property bag

- packages/reporter/src/formatters/sarif-formatter.ts
- packages/reporter/test/__snapshots__/sarif-formatter.test.ts.snap
- packages/reporter/test/__snapshots__/sonarqube-formatter.test.ts.snap
#498 
The misuse of sarif kind causes the level field not to display correctly. In the sarif reader, the display of sarif level is determined by sarif kind, in other words, sarif kind overwrites the value of the sarif level. 
Also changed to use sarif baselineState default value, which better suits our context.
> fix: correct use of sarif kind

- packages/cli/src/utils.ts
This flag allows us to emit code written in ES modules if it finds code written in CJS.
https://www.typescriptlang.org/tsconfig#esModuleInterop
Prior to this change when we ran across a `require` it would convert it to:
Given:
```js
const Foo = require("foo");
```
It would be converted to the following which is a non standard import only available in TS.
```ts
import Foo = require("foo");
```
With this flag it will be turned into what we would expect
```ts
import Foo from "foo";
```
> feat: use esModuleInterop

- packages/cli/src/helpers/report.ts
- packages/cli/test/fixtures/app/tsconfig.json
- packages/cli/test/fixtures/app_for_migrate/tsconfig.json
- packages/cli/test/fixtures/app_with_comments/tsconfig.json
- packages/cli/tsconfig.json
- packages/codefixes/tsconfig.json
- packages/migrate/tsconfig.json
- packages/migration-graph-ember/src/utils/discover-ember-packages.ts
- packages/migration-graph-ember/tsconfig.json
- packages/migration-graph-shared/tsconfig.json
- packages/migration-graph/tsconfig.json
- packages/plugins/tsconfig.json
- packages/reporter/tsconfig.json
- packages/service/tsconfig.json
- packages/upgrade/tsconfig.json
- packages/utils/tsconfig.json
Removes `baseURL` config in tsconfig. It's not necessary and causes import codeactions to prefix with `src/`.
> chore: remove baseurl

- packages/cli/src/commands/migrate/tasks/convert.ts
For #570 
There is a bug during replace `js` file extension name with `ts`. When a file path contains `js` in the middle of the string, the code would replace that `js` instead of the actual file extension. This PR uses regex to detect and replace the actual file extension.
> fix: file extension name replacement bug

- packages/cli/src/commands/migrate/tasks/initialize.ts
- packages/cli/test/commands/migrate.test.ts
- packages/migration-graph-ember/src/entities/ember-addon-package.ts
- packages/migration-graph-ember/src/entities/ember-app-package-graph.ts
- packages/migration-graph-ember/src/entities/ember-app-package.ts
- packages/migration-graph-ember/src/entities/ember-app-project-graph.ts
- packages/migration-graph-ember/src/utils/discover-ember-packages.ts
- packages/migration-graph-ember/test/entities/ember-app-package-graph.test.ts
- packages/migration-graph-ember/test/entities/ember-app-project-graph.test.ts
- packages/migration-graph-shared/src/entities/IPackage.ts
- packages/migration-graph-shared/src/entities/package-graph.ts
- packages/migration-graph-shared/src/entities/package.ts
- packages/migration-graph-shared/src/entities/project-graph.ts
- packages/migration-graph-shared/src/entities/root-package.ts
- packages/migration-graph-shared/test/entities/package.test.ts
- packages/migration-graph-shared/test/entities/project-graph.test.ts
- packages/migration-graph/src/migration-graph.ts
- packages/migration-graph/test/migration-graph.test.ts
- packages/migration-graph/test/migration-strategy.test.ts
- packages/test-support/src/library.ts
- pnpm-lock.yaml
* Adding package scope/boundary fixes #439.
* If a file is out of the package directory is is omitted from the module graph.
* Issue #567 is a problem with the include/exclude patterns for a package. To resolve this we need to always include the package.json files properties, and include all `**/*.js` files for a plain JS library.
> feat: include/exclude patterns; add package scope

- packages/cli/src/helpers/report.ts
- packages/cli/test/commands/migrate.test.ts
- packages/migrate/src/migrate.ts
This PR fixes 1 of 2 issues with SIGINT being ignored by a child process. This specific issue being fixed is around execa child process, which it would ignore SIGINT with `git mv`. By leveraging native `execSync` this issue is resolved.
Follow-Up PR for issue 2 of 2 which appears to be coming from here at a top level: https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/migrate/src/migrate.ts#L110
> fix: control-c during git mv

- packages/migrate/package.json
- packages/migration-graph-ember/src/entities/ember-addon-package.ts
- packages/migration-graph-ember/src/entities/ember-app-package.ts
- packages/migration-graph-shared/src/entities/package-graph.ts
- packages/migration-graph-shared/src/entities/package.ts
- packages/migration-graph-shared/test/entities/package.test.ts
- This is the minimal set of changes for adding include/exclude patterns API for a Package. 
- Originally landed in #575 before having been reverted.
- This API allows for us to more pragmatically add patterns to the packages as they're instantiated.
- This PR makes no changes in how we crawl a package, just the API.
> feat: include exclude patterns from module graph

- packages/cli/package.json
- packages/cli/src/commands/migrate/index.ts
- packages/cli/src/commands/migrate/tasks/convert.ts
- packages/cli/src/utils.ts
- pnpm-lock.yaml
This is PR fixes #579 by isolating `convertTask` with `simple` renderer in interactive mode.
Also added a simple git diff prettier for better display, using red BG for deletion and greed BG for addition.
See the video demo for how it works:
https://user-images.githubusercontent.com/2744803/211660015-4af29cfd-02bb-43d3-b72b-5a20b6a6f892.mov
> Fix: terminal based editor in interactive mode

- packages/migration-graph-shared/src/entities/package-graph.ts
- packages/migration-graph-shared/src/entities/package.ts
- packages/migration-graph-shared/src/entities/project-graph.ts
- packages/migration-graph-shared/src/entities/root-package.ts
- packages/migration-graph/src/migration-graph.ts
- packages/migration-graph/test/migration-graph.test.ts
Creates a `RootPackage` for a project is the root package.json excluding workspaces. Allfound packages in project will have an edge/dependency on this package.
- Updated tests.
- Root package should come last.
- Moves all root package instantiation into `.discover()` methods in the `ProjectGraph` implementations.
This package requires #588 to land first.
> feat: root package

- packages/migration-graph-ember/package.json
- packages/migration-graph-ember/src/entities/ember-addon-package.ts
- packages/migration-graph-ember/src/entities/ember-addon-project-graph.ts
- packages/migration-graph-ember/src/entities/ember-app-package.ts
- packages/migration-graph-ember/src/entities/ember-app-project-graph.ts
- packages/migration-graph-ember/src/mappings-container.ts
- packages/migration-graph-ember/src/utils/ember.ts
- packages/migration-graph-ember/tsconfig.json
- packages/migration-graph-shared/src/entities/package.ts
- packages/migration-graph-shared/src/entities/project-graph.ts
- packages/migration-graph-shared/test/entities/package.test.ts
- packages/migration-graph-shared/tsconfig.json
- packages/migration-graph/tsconfig.json
* Fix for "TS2376: A 'super' call must be the first statement in the constructor when a class contains initialized properties, parameter properties, or private identifiers."
* This bug was only found when building the `cli` package and not from the root build.
* Refactor include/exclude API to use getters and setters that can be called after super.
* Removed unnecessary build flags in `migration-graph-shared` and `migration-graph-ember` packages.
* Refactored some types to reduce warnings.
> fix(migration-graph-ember): move super to first line

- packages/cli/src/commands/migrate/index.ts
- packages/cli/src/commands/migrate/tasks/initialize.ts
- packages/cli/src/types.ts
- packages/cli/test/commands/__snapshots__/migrate.test.ts.snap
- packages/cli/test/commands/migrate.test.ts
For #601
Adding `-d`/`--dryRun` option in migrate CLI, which will print all the files that will be attempted to be migrated, and skip all the other tasks.
> feat: add dry run option in migrate CLI

- packages/migrate/src/migrate.ts
This PR is a refactor of migrate and implements pull based plugins and file iteration via generators/iterators. 
The initial goal was this would mitigate the SIGINT issue with the prev blocking implementation, however doesn't appear to resolve it.
> refactor: migrate as pull based gen and itr

- packages/migration-graph/test/migration-graph.test.ts
- packages/test-support/src/library.ts
Add a test in the `migration-graph` package and add a fixture in `test-support` for a project where a package has loose files in the rootDir.
> chore(migration-graph): test for loose files in a package

- packages/migration-graph/test/migration-graph.test.ts
- packages/migration-graph/test/migration-strategy.test.ts
- packages/test-support/src/library.ts
Additional test at the `migration-graph` package for a workspace with an out-of-scope file.
> chore(migration-graph): improve workspace test with out-of-scope file

- packages/cli/package.json
- packages/codefixes/package.json
- packages/migrate/package.json
- packages/migration-graph-ember/package.json
- packages/migration-graph-shared/package.json
- packages/plugins/package.json
- packages/reporter/package.json
- packages/service/package.json
- packages/upgrade/package.json
- packages/utils/package.json
We don't need `src` folder to be published, [package-json#files](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#files)
> chore: remove `src` from tarballs

- packages/migration-graph-ember/src/entities/ember-app-package.ts
- packages/migration-graph-ember/src/entities/ember-app-project-graph.ts
- packages/migration-graph-ember/src/mappings-container.ts
- packages/migration-graph-ember/src/types.ts
- packages/migration-graph-ember/src/utils/discover-ember-packages.ts
- packages/migration-graph-ember/test/entities/ember-app-package.test.ts
- Creates a type `EmberProjectPackage` which is `EmberAppPackage | EmberAddonPackage | Package`.
- Helps reduce misuse around the code base.
- Consolidate types to a single file.
> chore(migration-graph-ember): tidy types

- packages/cli/src/commands/migrate/tasks/config-lint.ts
- packages/cli/src/user-config.ts
- packages/cli/test/commands/migrate.test.ts
For #624.
- Fixed installation bug if dependencies/devDependencies in custom config is empty
- Added condition to not run default eslint config if custom lint config is provided
> fix: issue with custom config

- packages/migration-graph-shared/src/entities/package.ts
- packages/migration-graph-shared/test/entities/package.test.ts
- packages/migration-graph-shared/test/entities/project-graph.test.ts
- packages/test-support/src/library.ts
When regressing migration graph against our internal list of JS libaries, these were the common files that should be ignored from the graph when we forgo passing an `--entrypoint` argument.
The following will be ignored by default
**Directories**
```
.yarn // yarn3 directory
dist
test
tests
```
```
.eslintrc.*
.babelrc.*
babel.config.* // Babel configs
Brocfile.js 
prettier.config.* // Prettier configs
karma.config.*
webpack.config.js
vite.config.ts
```
This is ultimately a short term fix until this lands: https://github.com/rehearsal-js/rehearsal-js/issues/602
> feat(migration-graph): ignore more files

- packages/migration-graph-ember/src/entities/ember-addon-package-graph.ts
- packages/migration-graph-ember/src/entities/ember-app-package-graph.ts
- packages/migration-graph-ember/src/entities/ember-app-package.ts
- packages/migration-graph-ember/src/entities/ember-app-project-graph.ts
- packages/migration-graph-ember/src/mappings-container.ts
- packages/migration-graph-ember/src/types.ts
- packages/migration-graph-ember/src/utils/discover-ember-packages.ts
- packages/migration-graph-ember/test/entities/ember-app-package.test.ts
- packages/migration-graph-ember/test/smoke.test.ts
- packages/migration-graph-shared/src/entities/package.ts
- packages/migration-graph-shared/src/entities/project-graph.ts
- packages/migration-graph-shared/src/entities/root-package.ts
- packages/migration-graph/src/migration-strategy.ts
There were three different methods for accessing Package.path. This consolidates everything to the `Package.path` getter.
> chore: refactor to use Package.path

- packages/cli/src/commands/migrate/tasks/config-lint.ts
- packages/cli/src/commands/migrate/tasks/config-ts.ts
- packages/cli/src/commands/migrate/tasks/convert.ts
- packages/cli/src/helpers/report.ts
- packages/cli/src/utils.ts
- packages/cli/test/commands/migrate.test.ts
For #623.
- Stage `tsconfig.json`, `.eslintrc.js`, `.rehearsal-eslintrc.js` and all generated reports in the CLI, so that user won't need to do `git add` manually.
- Add a few more test for lint config task.
> feat: commit all the config files during migration

- packages/migration-graph-ember/src/entities/ember-addon-package.ts
- packages/migration-graph-ember/test/entities/ember-addon-package-graph.test.ts
- packages/migration-graph/test/migration-graph.test.ts
- packages/migration-graph/test/migration-strategy.test.ts
Initially created this PR to ignore `index.js` but found another issue #533 that had a similar problem.
* For an ember addon, omit the `app` dir and `index.js` from the migration-graph.
* Updated tests.
> fix(migration-graph-ember): addon, ignore app and index.js

- package.json
- packages/cli/package.json
- packages/cli/test/commands/migrate.test.ts
- packages/cli/test/commands/upgrade.test.ts
- packages/cli/test/helpers/utils.test.ts
- packages/cli/test/test-helpers.ts
- packages/codefixes/package.json
- packages/codefixes/src/2571/fixtures/2571.ts.output
- packages/migrate/package.json
- packages/migration-graph-ember/package.json
- packages/migration-graph-ember/src/utils/ember.ts
- packages/migration-graph-shared/package.json
- packages/migration-graph-shared/src/index.ts
- packages/migration-graph/package.json
- packages/plugins/package.json
- packages/reporter/package.json
- packages/service/package.json
- packages/test-support/package.json
- packages/upgrade/package.json
- packages/upgrade/test/__snapshots__/upgrade.test.ts.snap
- packages/upgrade/test/fixtures/upgrade/ts-errors.ts.input
- packages/upgrade/test/fixtures/upgrade/ts-errors.ts.output
- packages/upgrade/test/fixtures/upgrade/ts-processed.ts.output
- packages/utils/package.json
- pnpm-lock.yaml
This PR bumps typescript to latest, bundles it within the cli and updates tests as needed with new version. Fixes #622
> fix: bundle typescript and bump

- packages/codefixes/package.json
- packages/migrate/package.json
- packages/migration-graph-ember/package.json
- packages/migration-graph-shared/package.json
- packages/migration-graph/package.json
- packages/plugins/package.json
- packages/service/package.json
- packages/test-support/package.json
- packages/upgrade/package.json
- packages/utils/package.json
Should fix this:
```
everbits-mn2:urn-utils everbits$ yarn explain peer-requirements pfd5be
➤ YN0000: @rehearsal/cli@npm:1.0.2-beta::...1.0.2-beta.tgz provides typescript@patch:typescript@npm::version=4.9.4&hash=7ad353 with version 4.9.4, which doesn't satisfy the following requirements:
➤ YN0000: @rehearsal/codefixes@npm:1.0.2-beta::...1.0.2-beta.tgz [ffb00] → >4.9 ✘
➤ YN0000: @rehearsal/migrate@npm:1.0.2-beta::...1.0.2-beta.tgz [7f7d8]       → >4.9 ✘
➤ YN0000: @rehearsal/plugins@npm:1.0.2-beta::...1.0.2-beta.tgz [5abd3]       → >4.9 ✘
```
https://jubianchi.github.io/semver-check/#/^4.9%20||%20^5.0/4.9.4
https://jubianchi.github.io/semver-check/#/^4.9%20||%20^5.0/5.0.1
Added 5.0 in advance :)
> Correct peerDependencies typescript version

- .eslintrc.js
- package.json
- packages/cli/package.json
- packages/codefixes/package.json
- packages/migrate/package.json
- packages/migration-graph-ember/package.json
- packages/migration-graph-shared/package.json
- packages/migration-graph/package.json
- packages/plugins/package.json
- packages/reporter/package.json
- packages/service/package.json
- packages/test-support/package.json
- packages/upgrade/package.json
- packages/utils/package.json
- pnpm-lock.yaml
- release.js
This PR fixes #620 and provides an easier method of publishing. NPM permissions are required for publishing and recursive monorepo publishing is supported.
The script is executed at the root monorepo directory via:
```
pnpm release [major|minor|patch|prerelease|version] [alpha|beta|etc]
```
OR 
```
node release.js [major|minor|patch|prerelease|version] [alpha|beta|etc]
```
> chore: release script

- release.js
Fix version in the published packages
> fix: bump version before running `npm build`

- packages/cli/package.json
- packages/cli/src/commands/migrate/index.ts
- packages/cli/src/commands/migrate/tasks/config-lint.ts
- packages/cli/src/commands/migrate/tasks/index.ts
- packages/cli/src/commands/migrate/tasks/regen.ts
- packages/cli/src/helpers/report.ts
- packages/cli/src/types.ts
- packages/cli/src/utils.ts
- packages/regen/package.json
- packages/regen/src/index.ts
- packages/regen/src/regen.ts
- packages/regen/test/__snapshots__/index.test.ts.snap
- packages/regen/test/eslintrc.js
- packages/regen/test/fixtures/output/test1.ts.output
- packages/regen/test/fixtures/output/test3.ts.output
- packages/regen/test/fixtures/output/test4.ts.output
- packages/regen/test/fixtures/src/test1.ts
- packages/regen/test/fixtures/src/test2.js
- packages/regen/test/fixtures/src/test3.ts
- packages/regen/test/fixtures/src/test4.ts
- packages/regen/test/index.test.ts
- packages/regen/test/tsconfig.json
- packages/regen/tsconfig.json
- pnpm-lock.yaml
- tsconfig.json
Closes #438 
1. regenerate migration report, with or without uncommitted code changes
2. check if ts config and eslint config exist before generating report
3. scan ts files to check for errors
4. what regen does: 
- remove existing rehearsal comments
- check ts errors and insert comments
- reformatting
- check lint errors
- sending ts errors and lint errors to reporter
> feat: add --regen option

- packages/cli/src/commands/migrate/index.ts
- packages/cli/src/commands/migrate/tasks/convert.ts
- packages/cli/src/commands/migrate/tasks/initialize.ts
- packages/cli/src/helpers/state.ts
- packages/cli/test/commands/migrate/__snapshots__/initialize.test.ts.snap
- packages/cli/test/commands/migrate/initialize.test.ts
- packages/cli/test/helpers/__snapshots__/state.test.ts.snap
- packages/cli/test/helpers/state.test.ts
For #637.
- Make sure all the file/package paths are relative in `migrate-state.json`
- Small cleanups
- New test in `initialize` to check the package selection menu and the state file
> fix: use relative path in state file

- packages/cli/src/commands/migrate/index.ts
- packages/cli/src/commands/migrate/tasks/index.ts
- packages/cli/src/commands/migrate/tasks/validate.ts
- packages/cli/test/commands/migrate/__snapshots__/e2e.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/validate.test.ts.snap
- packages/cli/test/commands/migrate/validate.test.ts
Add new validate task in rehearsal migrate CLI, since we would definitely need more validation steps in the future for framework migrations:
- Add check for `package.json`
- Move `--regen` warning message into validate task
This fixes #621
> feat(cli): validate task

- packages/cli/src/commands/migrate/tasks/validate.ts
- packages/cli/test/commands/migrate/__snapshots__/validate.test.ts.snap
- packages/cli/test/commands/migrate/validate.test.ts
Fixes #662 
Check if `.gitignore` contains `.rehearsal`. If so we show the message to update `.gitignore`, since we need `.rehearsal/*` to be committed.
> fix: .rehearsal in .gitignore

- packages/regen/package.json
For some weird reason `regen` version is behind other packages.
> fix: fix `regen` version

- packages/plugins/src/plugins/diagnostic-fix.plugin.ts
Apparently my assumption of the TypeScript language server swallowing download errors was incorrect. This try/catches attempts to download types.
> fix: when packages aren't found we need to swallow the error

- packages/cli/src/commands/migrate/tasks/initialize.ts
Before we would log out the `SourceFile` objects but we should list the paths.
Before:
After:
> fix: logging of migration order

- packages/migrate/src/migrate.ts
- packages/plugins/src/plugins/diagnostic-check.plugin.ts
- packages/plugins/src/plugins/diagnostic-fix.plugin.ts
- packages/plugins/src/plugins/index.ts
- packages/plugins/src/plugins/lint.plugin.ts
- packages/plugins/src/plugins/re-rehearse.plugin.ts
- packages/plugins/test/re-rehearse.plugin.test.ts
- packages/regen/package.json
- packages/regen/src/regen.ts
- packages/service/src/index.ts
- packages/service/src/plugin.ts
- packages/service/src/rehearsal-service.ts
- packages/service/test/rehearsal-service.test.ts
- packages/upgrade/src/upgrade.ts
Use `migrate` code as an example of a non-blocking solution for `PluginsRunner` :)
Now all 3 - `migrate`, `upgrade`, and `regen` utilizes the same code... and seem can be merged together because they are basically the same (except for a number of plugins and their configs. 
Also separated PluginOptions and PluginsRunnerContext
> fix: refactor blocking code from all plugins

- packages/cli/package.json
- packages/cli/rehearsal-config-schema.json
- packages/cli/src/configs/rehearsal-config.ts
- packages/cli/src/types.ts
- pnpm-lock.yaml
- Generate a schema for rehearsal-config.json
- Once checked in we can reference this in documentation and our internal `rehearsal-cli-config` utility.
- This is supporting #588
> feat: rehearsal-config.json schema

- packages/plugins/package.json
- packages/plugins/src/plugins/diagnostic-fix.plugin.ts
- packages/service/src/rehearsal-service-host.ts
- pnpm-lock.yaml
A simple solution for https://github.com/rehearsal-js/rehearsal-js/pull/695:
Save all processed `diagnostic + fix` and ignore them if we try to fix the same diagnostic with the same fix. 
Closes #695
> chore: skip fixes that didn't work

- packages/cli/src/commands/migrate/index.ts
- packages/cli/src/commands/migrate/tasks/config-lint.ts
- packages/cli/src/commands/migrate/tasks/config-ts.ts
- packages/cli/src/commands/migrate/tasks/create-scripts.ts
- packages/cli/src/commands/migrate/tasks/dependency-install.ts
- packages/cli/src/commands/migrate/tasks/validate.ts
- packages/cli/src/types.ts
- packages/cli/test/commands/migrate/__snapshots__/e2e.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/validate.test.ts.snap
- packages/cli/test/commands/migrate/e2e.test.ts
- packages/cli/test/commands/migrate/validate.test.ts
This fixes #692.
The PR adds check for report (`migration-report.xx`) existence, to decide if it is the first run or sequential runs. In sequential runs, these tasks would be skipped:
- git dirty check
- dep install
- ts config
- lint config
- inject scripts in `package.json`
For this one, I think checking report is good enough to prove if it is the first run or not, so there is no specific check for each configs in order to skip them. For example, we don't check `devDependencies` in `package.json`, to see if we need to skip the dep install tasks.
I'm open to add more specific checks if anyone thinks it's needed.
> feat: skip config tasks after first run

- packages/cli/package.json
- packages/cli/src/commands/migrate/tasks/convert.ts
- packages/cli/src/commands/migrate/tasks/regen.ts
- packages/cli/src/commands/upgrade.ts
- packages/cli/test/commands/upgrade.test.ts
- packages/cli/test/test-helpers/index.ts
- pnpm-lock.yaml
This moves imports that eagerly import typescript e.g. `import * as ts from "typescript";` to be lazily loaded as they are needed. As a result of this we should be able to remove the dependency on typescript and simply make it a devDependency.
> chore: lazy load modules who need typescript in cli

- packages/reporter/src/formatters/sonarqube-formatter.ts
- packages/reporter/test/__snapshots__/sonarqube-formatter.test.ts.snap
Closes #714 
We bump line number and column number for sarif reader by 1. Now we need to deduct by 1 for sonarqube.
> fix: correct line and column numbers for sonarqube

- packages/cli/package.json
- pnpm-lock.yaml
The `typescript` dep was moved to devDep in the last tag. Moving it back to `devDeps`.
> fix: return typescript back to devDeps

- packages/cli/src/commands/migrate/index.ts
- packages/cli/src/commands/migrate/tasks/config-ts.ts
- packages/cli/src/commands/migrate/tasks/create-scripts.ts
- packages/cli/src/types.ts
- packages/cli/test/commands/migrate/__snapshots__/create-scripts.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/e2e.test.ts.snap
- packages/cli/test/commands/migrate/create-scripts.test.ts
- packages/cli/test/commands/migrate/e2e.test.ts
- packages/cli/test/test-helpers/index.ts
Fixes #726
This adds a `--init` flag to `migrate` that allows us to quickly configure projects without actually migrating them fully.
> feat: init flag for migrate

- packages/test-support/package.json
- release.js
The `pnpm -r publish` is stuck because of node_modules in fixtures... 
We don't need those folders to do the release e anyway.
Fixes: #708
> fix: release script

- packages/cli/package.json
- packages/cli/rehearsal-config-schema.json
- packages/cli/src/commands/migrate/tasks/initialize.ts
- packages/cli/src/configs/rehearsal-config.ts
- packages/cli/src/user-config.ts
- packages/cli/test/commands/migrate/__snapshots__/e2e.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/initialize.test.ts.snap
- packages/cli/test/commands/migrate/e2e.test.ts
- packages/cli/test/commands/migrate/initialize.test.ts
- packages/migration-graph-shared/src/entities/package-graph.ts
- packages/migration-graph-shared/src/entities/package.ts
- packages/migration-graph-shared/src/entities/project-graph.ts
- packages/migration-graph-shared/test/entities/package.test.ts
- packages/migration-graph-shared/test/entities/project-graph.test.ts
- packages/migration-graph/src/migration-graph.ts
- packages/migration-graph/src/migration-strategy.ts
- packages/migration-graph/test/migration-strategy.test.ts
- packages/test-support/src/library.ts
- pnpm-lock.yaml
This will address the features outlined in #602 
This PR will fix: #605 
- https://linkedin.ghe.com/multiproduct/rehearsal-cli-config
- https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/src/user-config.ts
```
{
migrate: {
// Defaults: ...
include: ['tests'],
// Defaults are: 
exclude: ['docs', 'webpack.config.js']
}
``` 
- This can be a defined schema similar to [tracerbench tb-schema.json](https://raw.githubusercontent.com/TracerBench/tracerbench/master/packages/cli/tb-schema.json)
- Using this package https://www.npmjs.com/package/typescript-json-schema
- ~Include a specific file include/exclude for a given package.~
- ~A way to configure each package or just for the project, which files or directories to ignore.~
- ~Configure by package, all packages, or at the …
> feat(migration-graph): include exclude config

- packages/migration-graph-shared/src/entities/package-graph.ts
- packages/migration-graph-shared/test/entities/package-graph.test.ts
Fixes #733 
**Root Cause**
- DependencyCruiser included json files.
**Fix**
- Add `.json` file extension to excluded files in `PackageGraph`.
- Wrote a test for reproduction
- Regressed against [`supported`](https://github.com/supportedjs/supported)
```
➜  supported git:(main) ✗ node ../../rehearsal-js/packages/cli/bin/rehearsal.js migrate --dryRun
info:    @rehearsal/migrate 1.0.7-beta
✔ Validate project
✔ Initialize -- Dry Run Mode
✔ Install dependencies
✔ Update tsconfig.json
✔ Update .eslintrc.js
✔ Add package scripts
› List of files will be attempted to migrate:
.prettierrc.js
lib/util.js
lib/time/index.js
lib/output/messages.js
lib/output/cli-output.js
lib/output/csv-output.js
lib/policy-rules.js
lib/lts/index.js
lib/project/index.js
lib/project/multiple-projects.js
lib/help.js …
```
> fix(migration-graph): remove *.json from module graph

- packages/cli/rehearsal-config-schema.json
- packages/cli/src/commands/migrate/tasks/config-lint.ts
- packages/cli/src/commands/migrate/tasks/config-ts.ts
- packages/cli/src/commands/migrate/tasks/dependency-install.ts
- packages/cli/src/configs/rehearsal-config.ts
- packages/cli/src/user-config.ts
- packages/cli/test/commands/migrate/__snapshots__/config-lint.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/config-ts.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/dependency-install.test.ts.snap
- packages/cli/test/commands/migrate/config-lint.test.ts
- packages/cli/test/commands/migrate/config-ts.test.ts
- packages/cli/test/commands/migrate/dependency-install.test.ts
This PR adds hook support in user config:
- postIntall
- postTsSetup
- postLintSetup
Also change all command fields to accept either a `HookCommand` or `HookCommand[]`.
> feat: hooks in user config

- packages/reporter/src/formatters/sonarqube-formatter.ts
- packages/reporter/test/__snapshots__/sonarqube-formatter.test.ts.snap
For Sonarqube, line number starts from 1, column number starts from 0.
> fix: revert line number

- package.json
- packages/cli/package.json
- packages/codefixes/package.json
- packages/migrate/package.json
- packages/migration-graph-ember/package.json
- packages/migration-graph-shared/package.json
- packages/migration-graph/package.json
- packages/plugins/package.json
- packages/regen/package.json
- packages/reporter/package.json
- packages/service/package.json
- packages/test-support/package.json
- packages/upgrade/package.json
- packages/utils/package.json
- pnpm-lock.yaml
Running into 'no test suite found in file' error on local. Got it fixed by upgrading vitest.
> chore: update vitest to 0.28.5

- .github/workflows/smoke-test.yml
Fixes: #746 
The intention behind this PR is on every push/pr run this action: https://github.com/rehearsal-js/smoke-test/blob/master/.github/workflows/run-smoke-test.yml. 
The smoke-test-action will:
- download the master branch zip from https://github.com/rehearsal-js/rehearsal-js/archive/refs/heads/master.zip
- pack the tarball for the @rehearsal/cli from zip rather than from NPM and as file:dep
- run test suite from https://github.com/rehearsal-js/smoke-test/tree/master/test
- if the test suite passes this action should pass
The downsides with this implementation:
- we are downloading from master rather than from the PR/commit/branch. as such we will only have an integration pulse after PR merge into master (we still catch way before release and execute manually if needed)
- I would …
> test: smoke test gha

- packages/cli/src/commands/migrate/tasks/config-lint.ts
- packages/cli/src/commands/migrate/tasks/convert.ts
- packages/cli/src/commands/migrate/tasks/regen.ts
- packages/cli/src/commands/upgrade.ts
- packages/migrate/src/migrate.ts
- packages/migrate/test/index.test.ts
- packages/regen/src/regen.ts
- packages/reporter/src/reporter.ts
- packages/reporter/test/reporter.test.ts
1. renaming entry point file extension in the rehearsal report from js to ts after the file has been git moved to ts
2. some other code cleanups.
> fix: renaming entrypoint from js to ts for migrate

- packages/migration-graph-ember/package.json
- packages/migration-graph-ember/src/entities/ember-addon-package-graph.ts
- packages/migration-graph-ember/src/entities/ember-addon-package.ts
- packages/migration-graph-ember/src/entities/ember-app-package-graph.ts
- packages/migration-graph-ember/src/entities/ember-app-package.ts
- packages/migration-graph-ember/src/entities/types.d.ts
- packages/migration-graph-ember/src/utils/discover-ember-service-dependencies.ts
- packages/migration-graph-ember/src/utils/transform-gjs.ts
- packages/migration-graph-ember/test/entities/ember-addon-package-graph.test.ts
- packages/migration-graph-ember/test/entities/ember-app-package-graph.test.ts
- packages/migration-graph-ember/test/utils/__snapshots__/transform-gjs.test.ts.snap
- packages/migration-graph-ember/test/utils/discover-ember-service-dependencies.test.ts
- packages/migration-graph-ember/test/utils/transform-gjs.test.ts
- packages/migration-graph-shared/src/entities/package-graph.ts
- packages/test-support/src/project.ts
- pnpm-lock.yaml
This PR addresses #606 
Adds support for `.gjs` files to Ember PackageGraphs.
- Includes `.gjs` file extension for `EmberAppPackageGraph` and `EmberAddonPackageGraph` resolveOptions passed to dependency-cruiser.
- Added test for `EmberAddonPackage` due to bug found where resolve alias for ember-addon paths starting with moduleName where not mapping back to the addon directory when regressing against internal addon.
- Preprocess/transform `.gjs` files to remove `<template>` tags and use something more es parse-able.
- Added tests
- Regressed against internal addon `voyager-web/packages/addons/image-view-model` which has `.gjs` files. Produces graph edges correctly. 
**This is no longer a concern because I removed usage of `futureCruise` api that was experimental/unstable.**
- The …
> feat: support .gjs in Ember PackageGraphs

- packages/migration-graph-ember/src/entities/ember-addon-package-graph.ts
- packages/migration-graph-ember/src/entities/ember-addon-package.ts
- packages/migration-graph-ember/src/entities/ember-addon-project-graph.ts
- packages/migration-graph-ember/src/entities/ember-app-package-graph.ts
- packages/migration-graph-ember/src/entities/ember-app-project-graph.ts
- packages/migration-graph-shared/src/entities/package-graph.ts
- packages/migration-graph-shared/src/entities/project-graph.ts
Debugging the creation of `EmberAddonProjectGraph` or EmberAdonPackageGraph` can be tricky since the inheritance chain creates different namespaces for each `DEBUG_CALLBACK` from debug.
Adding `DEBUG=rehearsal:migration-graph-ember:ember-addon-project-graph*` will only emit stuff with that prefix, and that is a very small constructor as it extends `EmberAppProjectGraph`. See https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/migration-graph-ember/src/entities/ember-addon-project-graph.ts
Inheritance chain:
```
EmberAddonProjectGraph -> EmberAppProjectGraph -> ProjectGraph
EmberAddonPackageGraph -> EmberAppPackageGraph -> ProjectGraph
```
On all `ProjectGraph` and `PackageGraph` implementations add:
```
protected debug: Debugger = …
```
> chore(migration-graph): improve logging for inheritance

- packages/migration-graph-ember/src/entities/ember-addon-package.ts
- packages/migration-graph-ember/test/entities/ember-addon-project-graph.test.ts
- packages/migration-graph/test/migration-strategy.test.ts
Address bug found in #761 
In an `EmberAddonPackage` we ignore the `app` directory, this creates a problem as **dependency-cuiser** will ignore all directories that are named `app`.
**dependency-cruiser** users regex for all paths. So we can add a caret to `^app` so all paths leading with that will be dropped from the search.
> fix: exclude only root app dir in EmberAddonPackage

- packages/codefixes/src/typescript-codefix-collection.ts
- packages/upgrade/test/__snapshots__/upgrade.test.ts.snap
- packages/upgrade/test/fixtures/upgrade/ts-types.ts.input
- packages/upgrade/test/fixtures/upgrade/ts-types.ts.output
Fix for a particular case with broken function declaration comes from "Type form JSDoc".
The test case contains another, more broad case where CodeFix returns correct but not existent type from JSDoc will be handled in an [issue](https://github.com/rehearsal-js/rehearsal-js/issues/790)  
Closes #775
> fix: filter out broken function types comes from JSDocs

- .github/workflows/smoke-test.yml
- .github/workflows/test-and-lint.yml
- vitest.config.js
This PR should enable us to run the smoke test against the pr branch. 
Prior to this commit we would only run the smoke test against the master branch, which would leave us in the state where master was 🔴 . This prevented us from releasing broken software but ideally we want to shift left and test our PRs against the smoke test app prior to merging. 
- I added names to the workflow file so they look nicer
- There is no need to have the vitest config to be a `.ts` file now that we are in ESM. Master seems to be broken because this config can't be loaded.
> chore: run smoke on branch

- packages/migration-graph-ember/src/entities/ember-addon-package.ts
- packages/migration-graph-ember/src/entities/ember-app-package.ts
- packages/migration-graph-ember/src/utils/excludes.ts
- packages/migration-graph-ember/test/entities/ember-addon-package.test.ts
- packages/migration-graph-ember/test/entities/ember-app-package.test.ts
- packages/migration-graph-ember/test/fixtures/package-fixtures.ts
- packages/migration-graph-shared/src/entities/package.ts
- packages/migration-graph-shared/src/index.ts
- packages/migration-graph-shared/src/utils/excludes.ts
- packages/migration-graph-shared/test/entities/package.test.ts
Fixes #813, #761
* `.rehearsal-eslint.js` excludes in all packages
* `.eslintrc.js` was not being excluded in ember package entities. Refacotred to pass package excludes to ember entities.
*  Adds ember-template-lint `.template-lintrc.js` to common ember excludes.
* Refactored excludes to stand alone files in packages
* Ember excludes extend from `migration-graph-shared` default excludes.
* Add tests for Packages validating excluded files and directories.
> fix: refactor excluded files in ember package entites

- packages/migration-graph-ember/src/entities/ember-addon-package.ts
- packages/migration-graph-ember/src/entities/ember-app-package-graph.ts
- packages/migration-graph-ember/src/entities/ember-app-package.ts
- packages/migration-graph-ember/src/utils/excludes.ts
- packages/migration-graph-ember/test/entities/ember-addon-package.test.ts
- packages/migration-graph-ember/test/entities/ember-app-package.test.ts
- packages/migration-graph-ember/test/fixtures/package-fixtures.ts
- packages/migration-graph-shared/src/entities/package.ts
- packages/migration-graph-shared/src/index.ts
- packages/migration-graph-shared/src/utils/excludes.ts
- packages/migration-graph-shared/test/entities/package.test.ts
This fixes #817 
Addons typically will re-rexport all things that can be used in an app in the `app/` at the root of an addon. In some cases internally (learning-web), all the in-repo addons lack a `app/` directory to re-export things. This breaks the migration graph.
- Changing the path lookup to `r/app/addon` for service resolution;
- Improve error message for service resolution with `source` and `dest` files for improved debugging:
```
Error: Unexpected error when parsing /Users/jdoe/Code/some-app/lib/some-addon/addon/components/my-component.js. Attempting to resolve service "user" from module/package name "other-addon" in package: /Users/jdoe/Code/some-app/lib/other-addon.
```
- No added tests. The current tests validate that if there was a discovered service dependency we create an …
> fix(migration-graoph): change path for service resolution to addon dir

- README.md
- packages/cli/src/commands/migrate/index.ts
- packages/cli/src/commands/migrate/init-command.ts
- packages/cli/src/commands/migrate/tasks/convert.ts
- packages/cli/src/commands/migrate/tasks/initialize.ts
- packages/cli/src/types.ts
- packages/cli/test/commands/migrate/__snapshots__/e2e.test.ts.snap
- packages/cli/test/commands/migrate/config-ts.test.ts
- packages/cli/test/commands/migrate/convert.test.ts
- packages/cli/test/commands/migrate/e2e.test.ts
- packages/cli/test/commands/migrate/initialize.test.ts
- packages/cli/test/commands/migrate/regen.test.ts
- packages/cli/test/commands/migrate/sequential.test.ts
- packages/cli/test/test-helpers/index.ts
- packages/codefixes/src/fixes/addMissingTypesBasedOnInheritance/index.ts
- packages/codefixes/src/fixes/addMissingTypesBasedOnInlayHints/index.ts
- packages/reporter/test/reporter.test.ts
- packages/service/src/rehearsal-service.ts
This PR makes `--interactive` the default and removes the need for the flag. Additionally it adds a new flag `--ci` which is the inverse of interactive.
@chadhietala `--ci` will need to be updated for all automated scripts / actions
> feat(cli): migrate default interactive - optional ci

- .github/workflows/test-and-lint.yml
To speed up scenario testing. Followed the direction of [this page](https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time). Changed the output of the store_output variable from what the instruction says, to avoid a pnpm bug: pnpm store will return a multiline string for path.
> chore: enable pnpm caching in github action

- .github/workflows/get-diagnostics.yml
I believe we need to pass in this PAS token so we don't get [protect brach errors](https://github.com/rehearsal-js/rehearsal-js/actions/runs/4462920273/jobs/7837784315). @lynchbomb is there anything special with permissions to use this token?
> fix: use PAS token

- packages/migrate/test/fixtures/project/src/salutation.hbs
- packages/migrate/test/fixtures/project/src/salutation.js
- packages/migrate/test/migrate.test.ts
- packages/plugins/src/plugins/diagnostic-check.plugin.ts
Should fix the issue where `migrate` was stalling out when converting TS/HBS file pairs.
When running the `diagnostic-check` plugin, we'd get the file's contents by calling `diagnostic.file.getFullText()`. In regular JS files, this is fine, but when you have a `gjs` file or `ts`/`hbs` pair, `getFullText` returns the Glint-transformed version of the file (which is basically unusable to the rest of rehearsal).
To handle this, we can instead use `service.getFileText` and pass in the filename from `diagnostic.file`.
> fix: use service to read file text for diagnostics

- packages/migration-graph-ember/src/entities/ember-app-package-graph.ts
- packages/migration-graph-ember/test/entities/ember-app-package-graph.test.ts
This fixes #822 
- There are two scenarios, we are looking within an app, or within an addon.
- For either service implementation we have to see if there is a file with a `.ts` or a `.js` extension on disk.
> fix(migration-graph): look for service impl be either .js or .ts

- .github/failed_cron_job_issue_template.md
- .github/workflows/ts-nightly-test.yml
> @chadhietala 
> This adds a github action job to run the entire test suite against nightly builds of TypeScript. Ideally in the future we should use rehearsal it self to do this but this will have to work until then.
> 
> This will allows us to get ahead of any breakage since we generously use the compiler api.
This PR includes running typescript@next on a daily cron job rather than against every PR. As TypeScript could introduce a bug in the nightly build which could block PR's.
Replaces #854
> chore(ci): test against typescript nightly

- packages/cli/src/commands/migrate/tasks/config-lint.ts
- packages/cli/src/commands/migrate/tasks/config-ts.ts
- packages/cli/src/commands/migrate/tasks/dependency-install.ts
Clear bottom bar messages after completion. e.g. the `tsconfig.json already exists` message at the bottom in the above screenshot should be removed after it's done.
> feat(cli): clear messages in bottom bar after completion

- packages/cli/package.json
- packages/cli/src/commands/migrate/tasks/analyze.ts
- packages/cli/src/commands/migrate/tasks/config-ts.ts
- packages/cli/test/commands/migrate/__snapshots__/analyze.test.ts.snap
- packages/cli/test/commands/migrate/analyze.test.ts
- packages/cli/test/commands/migrate/config-ts.test.ts
- packages/cli/test/commands/migrate/convert.test.ts
- packages/cli/test/commands/migrate/e2e.test.ts
- packages/cli/test/test-helpers/index.ts
- packages/cli/test/test-helpers/init-command-test-utils.ts
- packages/migrate/src/migrate.ts
- packages/regen/src/regen.ts
- packages/utils/package.json
- packages/utils/src/cli.ts
- pnpm-lock.yaml
In parts of CLI package we were using `readJSONSync` from `fs` for reading `tsconfig.json`. This doesn't work for `.json` files that have comments, or unquoted keys.
See #876 for example where an internal `tsconfig.json` from the jeeves task created config with a comment.
- **packages/util/** Add `readTSConfig` method using `json5.parse()`
- **packages/util** Refactored `writeTSConfig()` to allow for passing of a config data. Expose defaults at DEFAULT_TS_CONFIG.
- **packages/cli** Refactor usages where reading and writing to `tsconfig.json` to use  `readTSConfig` and `writeTSConfig` from `@rehearsal/util`.
- **packages/cli** Refactor tests in `analyze.test.ts` to setup and tear down projects more succinctly using the fixturify API.
- Usage of `json5` in **packages/cli** as it's no longer …
> fix: refactor to use json5.parse for read of tsconfig

- packages/service/package.json
- pnpm-lock.yaml
This PR fixes an incorrect import of @rehearsal/test-support as a bundled dependency of @rehearsal/service. This should be a dev-dependency only.
> fix(service): move test-support to devDep

- packages/cli/vitest.config.slow.ts
hookTimeout is causing slow test to fail. See: https://github.com/rehearsal-js/rehearsal-js/actions/runs/4545066769/jobs/8011901026?pr=875
This PR will unblock [PR #875](https://github.com/rehearsal-js/rehearsal-js/pull/875)
> chore: extends hookTimeout

- packages/utils/src/cli.ts
- packages/utils/test/cli.test.ts
We cannot rely on using `<package manager> bin` to get the bin dir for executables, since `npm>=9` already dropped the subcommand `bin`.
Assuming there is a executable `foo`:
I think it still better to try `<package manager> bin foo` first, then fallback to check if `foo` exists in `node_modules/.bin/foo` and return `node_modules/.bin` as the dir.
It is complicated to test in different scenarios, since we need to create "fake" `npm/yarn/pnpm` with different versions. There would be a high risk to pollute other tests and cause conflict so I just added a TODO in the test.
> fix: unable to get bin path with npm@9

- packages/cli/test/commands/migrate/__snapshots__/config-ts.ember-addon.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/config-ts.ember-app.test.ts.snap
- packages/cli/test/commands/migrate/config-ts.ember-addon.test.ts
- packages/cli/test/commands/migrate/config-ts.ember-app.test.ts
- packages/cli/test/test-helpers/config-ts-test-utils.ts
This PR is the most important part of the original PR #870. This PR is created for readability.
It adds ember tests for the `config-ts` task. The iterations look small, but each of them is a full iteration of the `config-ts` task under different conditions.
> test: add config-ts ember tests

- packages/cli/src/commands/migrate/tasks/config-ts.ts
- packages/cli/test/commands/migrate/__snapshots__/config-ts.ember-addon.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/config-ts.ember-app.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/config-ts.test.ts.snap
- packages/cli/test/commands/migrate/config-ts.ember-addon.test.ts
- packages/cli/test/commands/migrate/config-ts.ember-app.test.ts
- packages/cli/test/commands/migrate/config-ts.test.ts
Fixes #920
`tsConfigTask` should be triggered if:
- `tsconfig.json` does not exist, Or
- it is not in strict mode, Or
- user config for `ts-setup` exists
> fix: do not skip config-ts if user config exists

- packages/cli/src/commands/migrate/tasks/analyze.ts
- packages/cli/src/commands/migrate/tasks/config-lint.ts
- packages/cli/src/commands/migrate/tasks/config-ts.ts
- packages/cli/src/commands/migrate/tasks/dependency-install.ts
- packages/cli/src/commands/migrate/tasks/regen.ts
- packages/cli/test/commands/migrate/__snapshots__/analyze.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/config-lint.ember-addon.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/config-lint.ember-app.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/config-lint.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/config-ts.ember-addon.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/config-ts.ember-app.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/config-ts.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/convert.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/dependency-install.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/e2e.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/init-command.ember-addon.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/init-command.ember-app.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/init-command.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/regen.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/sequential.test.ts.snap
- packages/cli/test/commands/migrate/analyze.test.ts
- packages/cli/test/commands/migrate/config-lint.ember-addon.test.ts
- packages/cli/test/commands/migrate/config-lint.ember-app.test.ts
- packages/cli/test/commands/migrate/config-lint.test.ts
- packages/cli/test/commands/migrate/e2e.test.ts
- packages/plugins/src/plugins/transform.plugin.ts
- packages/utils/src/cli.ts
This PR adds a new feature to the CLI where we now set the resolution of the installed version of typescript in the package.json of the consuming app. Additionally it cleans up some minor copy issues, typo's where found and adds a [DEBUG](https://github.com/rehearsal-js/rehearsal-js/blob/67f1792d1e70c78298871c8f6e927588a2e5041a/packages/plugins/src/plugins/transform.plugin.ts#L21) statement in the transforms plugins exposing the ts compiler version directly.
The core features for review of this change are in two places:
- [util package for cli](https://github.com/rehearsal-js/rehearsal-js/blob/67f1792d1e70c78298871c8f6e927588a2e5041a/packages/utils/src/cli.ts#L319-L413)
- [cli package for dependency install](https://github.com/rehearsal-js/rehearsal-js/blob/67f1792d1e70c78298871c8f6e927588 …
> feat(cli): set resolution of ts in migrated app

- packages/cli/src/commands/migrate/tasks/dependency-install.ts
- packages/cli/test/commands/migrate/__snapshots__/config-lint.ember-addon.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/config-lint.ember-app.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/dependency-install.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/init-command.ember-addon.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/init-command.ember-app.test.ts.snap
- packages/cli/test/commands/migrate/__snapshots__/init-command.test.ts.snap
- packages/cli/test/commands/migrate/dependency-install.test.ts
Fixes #919 
This PR refactors `shouldRunDepInstallTask` to avoid dependency install collision. The issue previously was if a project had a dependency in-which rehearsal was trying to install as a dev-dependency the package manager would logically throw. 
Before we install a dep or devDep we now check against both dep and devDep of the consuming application and only install the delta regardless of where its installed eg.
- rehearsal is trying to install prettier as a devDep
- migrating app has prettier as a dep
- rehearsal will NOT try and install prettier as a devDep
> fix(cli): dep install collision

- packages/plugins/src/plugins/diagnostic-report.plugin.ts
- packages/plugins/src/plugins/glint-report.plugin.ts
- packages/reporter/src/reporter.ts
- packages/upgrade/test/__snapshots__/upgrade.test.ts.snap
- packages/upgrade/test/fixtures/upgrade/module.ts
- packages/upgrade/test/fixtures/upgrade/ts-errors.ts
Closes https://github.com/rehearsal-js/rehearsal-js/issues/935
Make a path to a file in diagnostic messages relative.
For example, instead of:
```
/* @ts-expect-error @rehearsal TODO TS1192: Module '"/Users/brehuang/dev/core-web-i18n-preprocessors/lib/i18nStatement"' has no default export. */
```
the comment will look like this:
```
/* @ts-expect-error @rehearsal TODO TS1192: Module '"./lib/i18nStatement"' has no default export. */
```
Also modified the glint plugin code to use getHint to apply the `pre-process` step for diagnostic messages.
> fix: make path to file relative in hint messages

- packages/migrate/test/__snapshots__/migrate.test.ts.snap
- packages/migrate/test/migrate.test.ts
- packages/plugins/src/plugins/glint-report.plugin.ts
Update `glint-report` so that it only adds one todo comment for a given line, rather than stacking them up.
Closes https://github.com/rehearsal-js/rehearsal-js/issues/900
> fix: don't add multiple todo comments for the same line

- Supported-Fixes.md
- packages/codefixes/src/codefixesMessages.json
- packages/codefixes/test/ts-codefixes.test.ts
Temporary disable `requireInTs` codefix. 
Has to be enabled together with `convertToEsModule`
> chore: disable requireInTs codefix

- packages/cli/src/commands/migrate/tasks/dependency-install.ts
- packages/cli/test/commands/migrate/__snapshots__/dependency-install.test.ts.snap
Need to actually run `postInstall` hook post-install or else things get weird fast.
> fix: run post-install hooks after install

- packages/migrate/src/migrate.ts
We can't just use `readJSON` on tsconfig.json because they will have comments in them.
> fix: need to json5

- Supported-Fixes.md
- packages/codefixes/src/codefixes.ts
- packages/codefixes/src/codefixesMessages.json
- packages/codefixes/src/fixes/annotateWithStrictTypeFromJSDoc.ts
- packages/codefixes/test/__snapshots__/base-codefixes.test.ts.snap
- packages/codefixes/test/base-codefixes.test.ts
- packages/codefixes/test/fixtures/annotateWithStrictTypeFromJSDoc/index.ts
- packages/codefixes/test/ts-codefixes.test.ts
- packages/ts-utils/src/helpers/typescript-ast.ts
- packages/upgrade/test/__snapshots__/upgrade.test.ts.snap
Filtering all types come from JSDocs that can't be resolved.
The feature is implemented as a wrapper over `annotateWithTypeFromJSDoc` codefix and only available for non-glimmer projects.
The next PR will have a JSDoc clean-up part (https://github.com/rehearsal-js/rehearsal-js/issues/590). 
Closes https://github.com/rehearsal-js/rehearsal-js/issues/790
> feat: improved annotateWithTypeFromJSDoc codefix

- packages/codefixes/src/typescript-codefix-collection.ts
- packages/upgrade/test/__snapshots__/upgrade.test.ts.snap
- packages/upgrade/test/fixtures/upgrade/ts-never.ts
This filters out `never` types. It's almost never the case that `never` is the correct type when we are inferring from usage. It's more that the language server cannot see the type of the elements being set into the array. The test case is similar to what had seen in code bases.
Prior to these changes the arrays would get inferred as `never[]` which is clearly wrong.
> fix: filter out never type

- packages/migrate/package.json
- packages/migrate/src/glint-utils.ts
- packages/migrate/test/fixtures/project/packages/foo/package.json
- packages/migrate/test/fixtures/project/packages/foo/with-qualified-service.js
- packages/migrate/test/migrate.test.ts
- pnpm-lock.yaml
Closes https://github.com/rehearsal-js/rehearsal-js/issues/964
Uses https://www.npmjs.com/package/resolve-package-path to correctly resolve package paths even in cases where the `basePath` is not the same as `process.cwd` or the root of the project (e.g. when running something like `rehearsal migrate --package ./packages/foo` in a monorepo)
> fix: correctly resolve addon paths

- .github/workflows/get-diagnostics.yml
- .github/workflows/test-and-lint.yml
- .github/workflows/ts-nightly-test.yml
- package.json
- packages/cli/package.json
- packages/codefixes/package.json
- packages/migrate/package.json
- packages/migration-graph-ember/package.json
- packages/migration-graph-shared/package.json
- packages/migration-graph/package.json
- packages/plugins/package.json
- packages/regen/package.json
- packages/reporter/package.json
- packages/service/package.json
- packages/test-support/package.json
- packages/ts-utils/package.json
- packages/upgrade/package.json
- packages/utils/package.json
- pnpm-lock.yaml
This PR
- bumps Node to latest LTS (18.15.0)
- pnpm latest (8.2.0)
- regenerates lock file
- bumps both in all gh-actions
> chore(all): node env and pnpm to latest LTS

- packages/migrate/src/glint-utils.ts
- packages/migrate/src/migrate.ts
- packages/plugins/src/plugins/glint-fix.plugin.ts
- packages/service/src/glint-utils.ts
- packages/service/src/rehearsal-service.ts
Hopfully closes https://github.com/rehearsal-js/rehearsal-js/issues/975 by making all of the glint-related modules dynamic imports so that we don't even attempt to import things like `GlintService` when we're not in an ember project
> fix: use dynamic imports for glint-related modules

- packages/migrate/src/glint-utils.ts
- packages/plugins/src/plugins/glint-fix.plugin.ts
- packages/plugins/src/plugins/glint-report.plugin.ts
- packages/service/src/glint-service.ts
- packages/service/src/index.ts
- pnpm-lock.yaml
Follow up to https://github.com/rehearsal-js/rehearsal-js/pull/983
We now just dynamically import all glint-related modules (including `@glint/core`) so that Node should never try to resolve a glint-related import unless one of the factory functions is called.
> fix: dynamic import all glint things

- packages/codefixes/src/fixes/addMissingTypesBasedOnInheritance.ts
- packages/codefixes/src/get-diagnostics.ts
- packages/codefixes/test/__snapshots__/base-codefixes.test.ts.snap
- packages/migrate/test/migrate.test.ts
- packages/plugins/src/plugins/diagnostic-fix.plugin.ts
- packages/plugins/src/plugins/glint-fix.plugin.ts
- packages/plugins/src/plugins/index.ts
- packages/upgrade/test/__snapshots__/upgrade.test.ts.snap
- packages/upgrade/test/fixtures/upgrade/ts-errors.ts
This is a follow on to #977 to move code modification to use magic-string for change tracking. Like #977, we are moving to a more conservative model to limit the amount of modifications we do, however instead of keeping track of lines we edit we track offsets relative to the original file. This obviously limits the amount of errors we can fix, however we need to draw a baseline of conservative but reproducible outcomes. We can expand the types we allow through at the same offset in the future.
I noticed that we were relying on re-checking the file of each turn of the loop to resolve parameter types in `addMissingTypesBasedOnInheritance`, however we can [continue walking up](https://github.com/rehearsal-js/rehearsal-js/pull/987/files#diff-17e38cc310e673b5b57aae2003b38325b0bfba76cc2dac216bff …
> internal: use magic-string for fixing

- packages/migrate/src/glint-utils.ts
- packages/migrate/src/migrate.ts
- packages/migrate/test/migrate.test.ts
- packages/plugins/src/plugins/diagnostic-comment.plugin.ts
- packages/plugins/src/plugins/diagnostic-fix.plugin.ts
- packages/plugins/src/plugins/diagnostic-report.plugin.ts
- packages/plugins/src/plugins/glint-comment.plugin.ts
- packages/plugins/src/plugins/glint-fix.plugin.ts
- packages/plugins/src/plugins/glint-report.plugin.ts
- packages/plugins/src/plugins/index.ts
- packages/plugins/src/plugins/lint.plugin.ts
- packages/plugins/src/plugins/prettier.plugin.ts
- packages/plugins/src/plugins/re-rehearse.plugin.ts
- packages/plugins/src/plugins/transform.plugin.ts
- packages/plugins/test/lint.plugin.test.ts
- packages/plugins/test/prettier.plugin.test.ts
- packages/plugins/test/re-rehearse.plugin.test.ts
- packages/regen/src/regen.ts
- packages/service/src/index.ts
- packages/service/src/plugin.ts
- packages/service/test/plugin-runner.test.ts
- packages/upgrade/src/upgrade.ts
This PR restructures the plugin execution loop and provides an abstract base class that plugins can inherit from. Prior to these changes we had to [reset the class state](https://github.com/rehearsal-js/rehearsal-js/pull/988/files#diff-11e3e65b5b4fefbcc62fbc0826e0036b9a8755b79ad29a33ff8149b126a17152L205) on a per file basis. Instead of registering instances into the queue we can register the constructors and let the queue executor be responsible for constructing them with the correct options. 
This PR does not change any user facing behavior and only cleans up how we author, execute and register plugins.
> internal: restructure plugins

- packages/migration-graph-ember/src/utils/discover-ember-service-dependencies.ts
- packages/migration-graph-ember/test/utils/discover-ember-service-dependencies.test.ts
Add support for import specifiers `service` to migraiton-graph-ember. Fixes #998 
We currently support this API when parsing a file for services usage:
`ember@3.28`
```
import { inject as service } from '@ember/service';
```
For `ember@>=4` we need to support the following.
```
import { service } from '@ember/service';
```
This PR adds checks for the service import specifier and any re-assignment of that exported name.
> feat: add support for ember@4 service exported method.

- package.json
- pnpm-lock.yaml
- scripts/processDiagnosticsAndFixes.mjs
This removes the last reference to glob in favor of fast-glob. The reason is to get around some licensing issues.
> chore: move to fast-glob

- packages/cli/test/commands/move/__snapshots__/move.test.ts.snap
- packages/migrate/src/migrate.ts
This change to allow placing a services-map.json to the project root when running migration on sub-package / addon.
> fix: search for services map in current and parent directories

- packages/cli/test/commands/move/__snapshots__/move.test.ts.snap
- packages/cli/test/commands/move/move.test.ts
- packages/cli/test/test-helpers/index.ts
In the 2.0.1-beta release the master went red due to the `move` tests emitting the current version into stdout and then captured by a snapshot. #1019 brought master back to green but did not resolve the problem. This PR resolves the problem by stabilizing stdout before generating the snapshot.
> chore: clean stdout for move tests

- packages/cli/test/commands/graph/__snapshots__/graph.test.ts.snap
- packages/cli/test/commands/graph/graph.test.ts
- packages/migration-graph-ember/src/entities/ember-addon-package-graph.ts
- packages/migration-graph-ember/test/entities/ember-app-project-graph.test.ts
- packages/migration-graph/test/migration-strategy.test.ts
- packages/test-support/src/files.ts
- packages/test-support/src/project.ts
This fixes an issue where [the only alias](https://github.com/rehearsal-js/rehearsal-js/pull/1023/files#diff-492c95ee8a02d9b520537e29d9c4e842e6fc84869da42e916061c3f754408e65R20-R23) we were create for addons was for the packageName but in reality these can be the packageName or the moduleName. This has been validated in our internal apps as well.
> fix: aliases need to look at modulename

- packages/migrate/src/migrate.ts
- packages/migrate/test/fixtures/project/.prettierrc
- packages/migrate/test/fixtures/project/src/already-migrated-js-to.ts
- packages/migrate/test/fixtures/project/src/already-migrated.gts
- packages/migrate/test/migrate.test.ts
- packages/plugins/src/plugins/glint-report.plugin.ts
- packages/plugins/src/plugins/transform.plugin.ts
The service injection transform plugin no detects if the property doesn't have a `declare` and steps in only in this case.
I also didn't duplicate comments if they are there before the property.
There is still issue with gts formatting, but those are related to glint files transformation :(
> fix: don't fix correctly declared services

- package.json
- packages/cli/package.json
- packages/cli/test/fixtures/app/package.json
- packages/cli/test/fixtures/app_for_migrate/src/basic_regen/package.json
- packages/codefixes/test/fixtures/package.json
- packages/migrate/test/fixtures/migrate/src/package.json
- packages/migrate/test/fixtures/project/package-lock.json
- packages/migrate/test/fixtures/project/package.json
- packages/migrate/test/fixtures/project/packages/foo/package.json
- packages/plugins/package.json
- packages/regen/package.json
- packages/regen/test/fixtures/src/package.json
- pnpm-lock.yaml
This PR fixes an issue we are seeing in #1030 and #1032. The root cause of the issue is that the version of eslint we are using in the root of the project is on an older version than the ones being installed into the tests. Normally this would be fine, but in this case certain rules [utilize the rules](https://github.com/typescript-eslint/typescript-eslint/blob/30f41aba51eb7a4ddc6cd5269489a1bc0d6a759b/packages/eslint-plugin/src/rules/no-empty-function.ts#L62) baked into eslint it self. So what is occurring is that the version in rehearsal was 8.33.0 but we were installing 8.40.0 where internally the `sourceCode` property was added to the context. 8.33.0 is being used to linting but the version that is being tested resolves to its own eslint version at 8.40.0, thus creating the errors.
> chore: fix eslint failures

- package.json
- packages/migrate/package.json
- packages/migrate/test/fixtures/project/package-lock.json
- packages/migrate/test/fixtures/project/package.json
- packages/migrate/test/fixtures/project/packages/foo/package.json
- packages/plugins/package.json
- packages/service/package.json
- pnpm-lock.yaml
This chore PR bumps @glint/core dep to latest release and out of beta
> chore: bumps @glint/core from 1.0.0-beta.4 to 1.0.2

- README.md
- Updated README with content from our internal TS Migration guide using new CLI commands.
> chore: update README.md with new CLI Command API

- packages/cli/src/commands/fix/command.ts
- packages/cli/src/commands/fix/tasks/initialize-task.ts
- packages/cli/src/commands/graph/tasks/graphOrderTask.ts
- packages/cli/src/commands/move/command.ts
- packages/cli/src/commands/move/tasks/initialize.ts
- packages/cli/src/types.ts
- packages/cli/test/commands/fix/__snapshots__/fix.test.ts.snap
- packages/cli/test/commands/move/__snapshots__/move.test.ts.snap
- packages/migrate/src/migrate.ts
- packages/migration-graph-ember/src/index.ts
- packages/plugins/src/plugins/re-rehearse.plugin.ts
This PR:
- adds an option to the cli graph task to skip the prompt. this is needed when consuming this task in other commands (move & fix)
- cleans up remnant code from a previous refactor for ctx.package
> fix: removed remnant package from ctx and adds skipPrompt for graph

- packages/cli/src/commands/fix/command.ts
- packages/cli/src/commands/fix/tasks/convert-task.ts
- packages/cli/src/commands/fix/tasks/initialize-task.ts
- packages/cli/src/commands/move/command.ts
- packages/cli/src/commands/move/tasks/mv.ts
- packages/cli/src/types.ts
- packages/cli/test/commands/fix/init-task.test.ts
This PR:
- removes `dryRun` from CLI command `fix` as its not supported
> chore(cli): remove unused dryRun

- packages/cli/src/commands/graph/tasks/graphOrderTask.ts
- packages/migration-graph-shared/src/entities/package-graph.ts
This adds the ability to turn off the worker thread by passing envar `WORKER=false`. This can be used in conjunction with `DEBUG=` and `node --inspect-brk`. This is working around some issues related to debuggability of worker_threads.
> chore: better debugging in graph

- packages/migrate/src/migrate.ts
- packages/migrate/test/__snapshots__/migrate.test.ts.snap
- packages/migrate/test/fixtures/project/packages/moo/package.json
- packages/migrate/test/fixtures/project/packages/moo/with-qualified-service.ts
- packages/migrate/test/migrate.test.ts
- packages/service/package.json
- packages/service/src/rehearsal-service-host.ts
- pnpm-lock.yaml
Fix the case when the target package doesn't have a tsconfig.json file and the parent one is used.
> fix: fix the path to load tsconfig.json

- packages/cli/test/commands/fix/init-task.test.ts
- packages/utils/src/cli.ts
- packages/utils/test/cli.test.ts
This PR:
- allows for "latest" in package.json as a viable version in pre-req check
> fix: preflight support for latest dep

- packages/utils/package.json
- pnpm-lock.yaml
Internal usage of `3.0.3` has a problem because find-up has the incorrect API for the package.
**Bug**
```bash
$ yarn rehearsal graph -o migration-graph.json                                     
/node_modules/@rehearsal/utils/dist/src/cli.js:3
import { findUpSync } from 'find-up';
^^^^^^^^^^
SyntaxError: Named export 'findUpSync' not found. The requested module 'find-up' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from 'find-up';
const { findUpSync } = pkg;
at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
at async Promise.all (index 0)
at async ESMLoader.import …
```
> fix(util): move find-up to dependency

- packages/cli/src/commands/fix/command.ts
- packages/plugins/src/plugins/diagnostic-fix.plugin.ts
- packages/smoke-test/test/commands/__snapshots__/fix.test.ts.snap
- packages/smoke-test/test/commands/fix.test.ts
In #1067 we regressed as we needed to check to see if we are passing a directory or a file path. A file path is validated downstream.
> fix: generate globs only for directories

- packages/migration-graph/src/resolver.ts
- packages/migration-graph/test/resolver.test.ts
This removes the invariant assert for when an import has a relative path that never exists. This is typically the case with files that conventional exist only at build time.
> fix: remove invariant in graph

- packages/migrate/README.md
- packages/migrate/test/__snapshots__/migrate.test.ts.snap
- packages/migrate/test/fixtures/project/.rehearsal/services-map.json
- packages/migrate/test/fixtures/project/src/with-addon-service.gts
- packages/migrate/test/fixtures/project/src/with-addon-service.ts
- packages/migrate/test/fixtures/project/src/with-mapped-service.gts
- packages/migrate/test/fixtures/project/src/with-mapped-service.ts
- packages/migrate/test/migrate.test.ts
- packages/plugins/src/plugins/transform.plugin.ts
This fixes #1087.
- Prioritizes the `.rehearsal/service-map.json` resolution over our derivation logic.
- This will allow any future service resolution issues to be short circuited with simply adding a entry to `services-map.json`, rather than waiting for parsing to fail. 
- Improves service strings parsing to support a packageName.
- This is an internal problem used in some 400+ places in voyager-web. 
```
@service('jet') jet; 
@service('some-module-name@foo') foo;
@service('@some-org/some-package@locale') locale; // This support was added./
```
> fix: fix service string resolution to support package with org in transform plugin 

- packages/migrate/test/__snapshots__/migrate.test.ts.snap
- packages/migrate/test/fixtures/project/src/gjs-no-errors.gts
- packages/migrate/test/fixtures/project/src/missing-local-prop.gts
- packages/migrate/test/fixtures/project/src/with-addon-service.gts
- packages/migrate/test/fixtures/project/src/with-addon-service.ts
- packages/migrate/test/fixtures/project/src/with-mapped-service.gts
- packages/migrate/test/fixtures/project/src/with-mapped-service.ts
- packages/migrate/test/fixtures/project/src/with-non-qualified-service.gts
- packages/migrate/test/fixtures/project/src/with-qualified-service.gts
- packages/migrate/test/migrate.test.ts
- `migrate.test.ts` has many `.gts` tests that don't work.
- This marks all bad tests with a `.todo`
- Modified input to have a unique signature.
- Adds assertions to output for said signature.
- See  #1087  with example test where snapshots are bad. 
- **This is not an issue with the snapshots needing an update**, but an issue where the output is incorrect given the input is inccorrect.
> chore(migrate): add test.todo on bad `.gts` tests

- packages/migration-graph/src/discover-services.ts
- packages/migration-graph/test/discover-services.test.ts
When parsing service meta we need to ensure we can get a packageName that contains an org.
- Adds test for discover-services.
- Restored from previous implementation.
- Updated test cases to work with new API. 
- Fixes bug where a service decorator is using a service from a package within an organziation.
- `@service('@my-org/some-package@some-service') myService;`
> fix(migration-graph): add support for resolving service from package within org

- packages/cli/src/commands/fix/tasks/convert-task.ts
- packages/cli/src/commands/fix/tasks/convertWorker.ts
- packages/codefixes/test/base-codefixes.test.ts
- packages/codefixes/test/suppressed-errors.test.ts
- packages/migrate/src/migrate.ts
- packages/migrate/test/__snapshots__/migrate.test.ts.snap
- packages/migrate/test/migrate.test.ts
- packages/plugins/test/utils.ts
- packages/reporter/src/formatters/md-formatter.ts
- packages/reporter/src/formatters/sarif-formatter.ts
- packages/reporter/src/reporter.ts
- packages/reporter/src/types.ts
- packages/reporter/test/__snapshots__/json-formatter.test.ts.snap
- packages/reporter/test/__snapshots__/markdown-formatter.test.ts.snap
- packages/reporter/test/__snapshots__/reporter.test.ts.snap
- packages/reporter/test/__snapshots__/sarif-formatter.test.ts.snap
- packages/reporter/test/fixtures/rehearsal-report.json
- packages/reporter/test/fixtures/rehearsal-run.json
- packages/reporter/test/fixtures/sarif-formatter/index.ts
- packages/reporter/test/reporter.test.ts
- packages/service/test/plugin-runner.test.ts
This PR:
- Fixes a bug where absolute paths in the report key `basePath` | `reportOutDir` was an absolute path.
- Refactors the @rehearsal/reporter report `summary` and removes legacy keys:
```
commandName
entrypoint
basePath
reportOutDir
```
- `commandName`: a given report can only be generated via `rehearsal fix` as such we dont need to explicitly call out which rehearsal command was used to generate the report (only 1 option)
- `entrypoint`: this is a remnant from previous API
- `basePath` | `reportOutDir`: `basePath` was renamed to `reportOutDir`. However,  the underlying value for this path just doesn't provide value. As this was only specifying the path in the report where the report itself resides.
> refactor: cleanup report summary

- packages/codefixes/src/hints.ts
Fixes #1085 
This PR:
- Adds a catch for `TS7016` where we return the hint without absolute paths and 'any' type comment, since its not super helpful.
- Removes the direction to leverage `npm` to install a missing type to `Try installing the missing type`.
**PREVIOUS**
// @ts-expect-error @rehearsal TODO TS7016: Could not find a declaration file for module 'ember-asset-loader/addon/services/asset-loader'. '/Users/medwards/Code/muuto/test-packages/voyager-web/node_modules/ember-asset-loader/addon/services/asset-loader.js' implicitly has an 'any' type. Try npm i --save-dev @types/ember-asset-loader if it exists or add a new declaration (.d.ts) file containing declare module 'ember-asset-loader/addon/services/asset-loader';
**CURRENT**
// @ts-expect-error @rehearsal TODO TS7016: Could not …
> fix(codefixes): handles hint for TS7016 removes absolute urls

- packages/migration-graph/src/dot.ts
- packages/migration-graph/test/__snapshots__/resolver.test.ts.snap
Because we place aliases into the global packages map we need to remove them when we print the dot output. Otherwise we will have duplicates and `dot` will yak if there are too many dups.
> fix: remove duplication in dot output

- packages/cli/src/commands/graph/tasks/graphOrderTask.ts
We forgot to thread `--externals` into the worker. The branching for the worker probably should be rethought so we don't make this mistake in the future.
> fix: thread external option

- packages/cli/test/commands/fix/__snapshots__/fix.test.ts.snap
- packages/migration-graph/src/resolver.ts
- packages/smoke-test/test/commands/__snapshots__/fix.test.ts.snap
- Ignoring `.hbs` files in graph because the GlintComment plugin cannot accurately inject a `{{! @glint-expect-error }}` comment that doesn't break syntax.
- This can be removed once #1119 is resolved.
> fix: ignore hbs files

- packages/codefixes/src/hints-codefix-collection.ts
- packages/migrate/test/__snapshots__/migrate.test.ts.snap
- packages/migrate/test/fixtures/project-basic/src/typedef.ts
- packages/migrate/test/fixtures/project/package-lock.json
- packages/migrate/test/fixtures/project/src/typedef.ts
- packages/migrate/test/migrate.test.ts
- packages/plugins/src/plugins/diagnostic-fix.plugin.ts
Some codefixes, like convertTypedefToType, can have no related AST node, so we don't need to filter them out.
Fixes: https://github.com/rehearsal-js/rehearsal-js/issues/1128
> fix: allow fixes without related AST node to be applied

- .github/failed_cron_job_issue_template.md
- .github/workflows/ts-beta-test.yml
The goal of this PR is to get a pulse of the stability of `beta` when running against the `1.*.*` release of Rehearsal (current)
This PR:
- updates the current `nightly` workflow to now run against `beta` version of typescript
- runs against both test and test:slow
> chore: workflow beta

- packages/cli/src/helpers/report.ts
- packages/cli/test/commands/fix/__snapshots__/fix.test.ts.snap
- packages/migrate/test/__snapshots__/migrate.test.ts.snap
- packages/migrate/test/fixtures/project/src/gts-with-errors.gts
- packages/migrate/test/fixtures/project/src/with-errors.hbs
- packages/migrate/test/fixtures/project/src/with-errors.ts
- packages/migrate/test/migrate.test.ts
- packages/migration-graph/src/resolver.ts
- packages/plugins/src/plugins/glint-comment.plugin.ts
- packages/plugins/src/plugins/glint-report.plugin.ts
- packages/reporter/src/index.ts
- packages/reporter/src/reporter.ts
- packages/reporter/src/types.ts
- packages/smoke-test/test/commands/__snapshots__/fix.test.ts.snap
Adds feature described in #1105 
- Re-enable parsing .hbs files in graph.
- Abort adding glint directives `{{! @glint-expect-error}}` to hbs contexts.
- Update reporter to aggregate glint errors.
- `fix` command output now prints total glint errors found
Changes across packages:
- Update CLI report output (fix) to optionally display **glint** error summary
- Adds a test in `migrate` package for validating the errors with `ReportItemType.glint` show on the reporter.
- Validates that glint errors for `ReportItemType.glint` exist in `rehearal-report.json` output.
- Adds `.hbs` back into graph creation
- I ignored .hbs after I discovered the injection issue.
- This is necessary so we can feed `.hbs` files into the GlintComment and GlintReport plugins.
- This will now show that …
> feat: add glint errors in output; drop comment insertion in hbs

- packages/migration-graph/src/resolver.ts
Fixes issue of walking through .d.ts files in `fix graph`
Fixes #1134
> fix: graph is trying to scan .d.ts files

- packages/migrate/test/__snapshots__/migrate.test.ts.snap
- packages/migrate/test/fixtures/project/src/gts/with-mapped-service.gts
- packages/migrate/test/fixtures/project/src/with-mapped-service.ts
- packages/migration-graph/src/discover-services.ts
- packages/migration-graph/test/discover-services.test.ts
- packages/plugins/src/plugins/transform.plugin.ts
We currently handle next service injection cases:
- `@service('some@service') someService`
- `@service('service') someService`
- `@service someService`
this PR covers:
- `@service() someService`
> fix: handle `@service() name` injection

- packages/cli/test/commands/graph/__snapshots__/graph.test.ts.snap
- packages/cli/test/commands/graph/graph.test.ts
- packages/cli/test/commands/move/__snapshots__/move.test.ts.snap
- packages/cli/test/commands/move/move.test.ts
- packages/cli/test/fixtures/base_js_app/module-c/package.json
- packages/cli/test/fixtures/base_js_app/module-c/src/index.js
- packages/cli/test/fixtures/base_js_app/module-c/types/global.d.ts
- packages/migration-graph/src/package-node.ts
- packages/service/package.json
This PR:
includes typesVersions as a viable key for package.json types in the migration-graph PackageNode class.
```
"typesVersions": {
"*": {
"*": [
"types/*"
]
}
}
```
> fix(migration-graph): expand hasTypes to include typesVersions check

- package.json
This should help dev to ensure that the right version of `pnpm` is used while both `corepack` (`packageManager`) and `volta` supports `pnpm` in experimental mode:
> chore: insure the right version of pnpm is used

- package.json
This PR changes the pnpm engine to be a min vs a specific version. Otherwise the GH Action will fail as mismatch.
> fix: engines pnpm from pin

- README.md
- Supported-Fixes.md
- packages/cli/src/commands/fix/command.ts
- packages/cli/test/commands/fix/__snapshots__/fix.test.ts.snap
- packages/codefixes/src/codefixesMessages.json
- packages/codefixes/src/get-diagnostics.ts
- packages/codefixes/test/__snapshots__/base-codefixes.test.ts.snap
- packages/codefixes/test/fixtures/base-codefixes/addMissingExport/4082-1-import.tsx
- packages/codefixes/test/fixtures/base-codefixes/addMissingExport/4082-1.tsx
- packages/codefixes/test/fixtures/base-codefixes/addMissingExport/4082-2.tsx
- packages/codefixes/test/ts-codefixes.test.ts
- packages/plugins/src/plugins/diagnostic-fix.plugin.ts
- packages/plugins/src/plugins/glint-fix.plugin.ts
- packages/plugins/src/plugins/glint-report.plugin.ts
- packages/smoke-test/test/commands/__snapshots__/fix.test.ts.snap
Add the `--mode` option to `fix` command. 
Makes `drain` default mode for fix.
PR includes next bug fixes and improvements:
- adds additional exit criteria to the loop of drain mode 
- prioritizes fix (TS80009) that converts typedefs to interfaces
- fixes "error fixed" report counter in drain mode
- fixes types of errors (suggestions) rehearsal is trying to fix in glint-fix plugin
- fixes the list of errors reported in glint-report plugin
- disables "Remove Unused Identifier" codefix
> feat: expose diagnostic fixing modes

- README.md
PR #1178 introduced an issue with the README.  The `--skipChecks` docs are added to the wrong command.  This fixes that issue.
> [chore] updated README so that docs for --skipChecks flag exist under info about rehearsal fix and not rehearsal move

- packages/codefixes/src/codefixes.ts
- packages/codefixes/src/fixes/stubMissingJSDocParamName.ts
- packages/codefixes/src/fixes/stubMissingNameJSDocParam.ts
- packages/codefixes/test/__snapshots__/base-codefixes.test.ts.snap
- packages/codefixes/test/fixtures/base-codefixes/stubMissingJSDocParamName/8024-jsdoc-missing-param-name.ts
- packages/migrate/test/__snapshots__/migrate.test.ts.snap
- packages/migrate/test/fixtures/project/src/gts/with-missing-jsdoc-param-name.gts
- packages/migrate/test/migrate.test.ts
This PR addresses #1192 
There is a use case in an internal app where a JSDoc `@param` is defined but has no variable name. This creates a case where we inject a rehearsal TODO into the doc block, and subsequent invocations of `rehearsal fix` will mangle the file after the affected region.
Transforming a doc block with this will cause a second pass with fix to mangle the output of the file there after.
```diff
/**
+   // @ts-expect-error @rehearsal TODO TS8024: JSDoc '@param' tag has name '', but there is no parameter with that name.
* @param {Event} -- Something
+   // @ts-expect-error @rehearsal TODO TS8024: JSDoc '@param' tag has name '', but there is no parameter with that name.
* @param {string} -- Another
+   // @ts-expect-error @rehearsal TODO TS8024: JSDoc '@param' tag has name …
```
> feat: stubMissingNameJSDocParam

- packages/codefixes/src/fixes/addMissingTypesBasedOnInheritance.ts
- packages/codefixes/src/get-diagnostics.ts
- packages/migrate/test/__snapshots__/migrate.test.ts.snap
- packages/migrate/test/fixtures/project-basic/src/basic.animal.ts
- packages/migrate/test/fixtures/project-basic/src/basic.food.ts
- packages/migrate/test/fixtures/project-basic/src/basic.index.ts
- packages/migrate/test/fixtures/project-basic/tsconfig.json
- packages/migrate/test/migrate.test.ts
- packages/service/src/rehearsal-service-host.ts
- packages/smoke-test/test/commands/__snapshots__/fix.test.ts.snap
- packages/smoke-test/test/commands/__snapshots__/graph.test.ts.snap
- packages/smoke-test/test/commands/fix.test.ts
- packages/smoke-test/test/fixtures/base_ts_app/src/basic.animal.ts
- packages/smoke-test/test/fixtures/base_ts_app/src/basic.food.ts
- packages/smoke-test/test/fixtures/base_ts_app/src/basic.index.ts
Prioritize "Fixes missing imports" error codes to make sure we don't have missing types before start types inferring process.
This helps to solve the issue when type are inferred from inheritance or from inlay type hints without been imported. The type will be imported next cycle (in drain mode) and the rest of codefixes expected to be applied without issues. 
Also fixes: 
- module resolutions on case-insensitive filesystems
Fixes https://github.com/rehearsal-js/rehearsal-js/issues/1187
> fix: import types when infer from inheritance

- packages/codefixes/src/typescript-codefix-collection.ts
Suppress the error happening during getCodeFixesAtPosition for TS7006 when TypeScript is struggling to detect the type.
The issues is happening during processing this kind of content:
```
import Route from '@ember/routing/route';
export default class BaseRoute extends Route {
setupController(controller, params) {
super.setupController(controller, params);
}
}
```
> fix: suppress issue with a type detection in inferFromUsage codefix

- packages/cli/test/commands/fix/__snapshots__/fix.test.ts.snap
- packages/migrate/test/__snapshots__/migrate.test.ts.snap
- packages/migrate/test/migrate.test.ts
- packages/plugins/src/plugins/glint-fix.plugin.ts
- packages/service/src/glint-service.ts
- packages/service/src/rehearsal-service.ts
- packages/smoke-test/test/commands/__snapshots__/fix.test.ts.snap
- packages/smoke-test/test/fixtures/base_ts_app/test/__snapshots__/main.test.ts.snap
Adds a `getAdditionalDiagnostics` function to Glint Service to infer return types based on inlay hints.
Also:
- Starting now, `.gts` files have `Method 'containsUnsupportedDiagnostic' lacks a return-type annotation.` comments over function with missing return type.
- `.ts` under Glint projects will have return types inferred where type hints are available..
- SourceFiles produced by Glint Service for .gts now compatible with TS helper functions, so base codefixes will be easier to run on them as well! :)
> fix: Glint Service is not inferring return types from inlay hints

- packages/codefixes/src/codefixes.ts
- packages/codefixes/src/fixes/addMissingTypesBasedOnInlayHints.ts
- packages/migrate/test/__snapshots__/migrate.test.ts.snap
- packages/migrate/test/fixtures/project/src/gts/with-missing-jsdoc-param-name.gts
Enable AddMissingTypesBasedOnInlayHintsCodeFix for .gts files
To do this we have to use .ts file extension when call `service.provideInlayHints` function because Glint's `program` doesn't know about .gts and represents them as .ts files under the hood.
This hack is plan to be removed during https://github.com/rehearsal-js/rehearsal-js/issues/1084
> fix: enable AddMissingTypesBasedOnInlayHintsCodeFix for .gts files

- packages/codefixes/src/fixes/glint/addMissingArgToComponentSignature.ts
- packages/migrate/test/__snapshots__/migrate.test.ts.snap
- packages/migrate/test/fixtures/project/src/gts/signatures/with-missing-args.gts
- packages/migrate/test/migrate.test.ts
This addresses #1228, Adds support for populating component signatures with usages like: `this.args.someParam` in `gts` files.
> feat(glint): add this.args usage to signature

- packages/codefixes/src/fixes/addMissingTypesBasedOnInlayHints.ts
- packages/codefixes/test/__snapshots__/base-codefixes.test.ts.snap
- packages/codefixes/test/fixtures/base-codefixes/addMissingTypesBasedOnInlayHints/ts-should-not-append-types-with-ellipsis.ts
- packages/smoke-test/test/commands/__snapshots__/fix.test.ts.snap
- packages/smoke-test/test/commands/__snapshots__/graph.test.ts.snap
- packages/smoke-test/test/fixtures/base_ts_app/src/greeting.ts
The text coming back from an inlay hint isn't always valid syntax, so we don't use inlay hint types if they have `...` three-periods (like an ellipsis but not the character code). 
Inlays hints may provide a list of a types that a function may return.
Given some code like the following:
```typescript
// Use Case
class Greeting<T> {
phrase;
constructor(phrase) {
this.phrase = phrase;
}
}
class SomeClass {
constructor() {}
someFunctionWithManyReturnTypes(arg1: boolean, arg2: boolean) {
let result;
if (arg1) {
result = 'Hello';
} else if (arg2) {
result = new Greeting<string>('Hey');
} else {
result = Promise.resolve(new Greeting<string>('Hola'));
}
return result;
}
}
```
The Inlay hints will suggest a return type for `someFunctionWithManyReturnTyupes` to be:
```
- …
```
> fix(codefix): drop inlay hints that contain `...`

- packages/migration-graph/src/resolver.ts
- packages/migration-graph/test/resolver.test.ts
This small PR improves the DX by implementing error handling when the migration-graph resolver chokes via `es-module-lexer:parse`. 
It isn't obvious why the `rehearsal graph` command is failing
```
rehearsal graph                               
yarn run v1.22.15
✖ Parse error @:17:22
node:internal/process/promises:279
triggerUncaughtException(err, true /* fromPromise */);
^
Error: Parse error @:17:22
at parse (file:///hue-web-foundations/node_modules/@rehearsal/migration-graph/node_modules/es-module-lexer/dist/lexer.js:2:358)
at Resolver.walk (file:///hue-web-foundations/node_modules/@rehearsal/migration-graph/dist/src/resolver.js:65:27)
at file:///hue-web-foundations/node_modules/@rehearsal/cli/dist/src/commands/graph/tasks/graphWorker.js:19:18 {
idx: 550
}
error Command failed with exit …
```
> fix: wrap es-module-lexer parse in a try/catch better error handling

- packages/migrate/test/__snapshots__/migrate.test.ts.snap
- packages/migrate/test/fixtures/project/src/gts/foo.gts
- packages/migrate/test/migrate.test.ts
- packages/plugins/src/plugins/diagnostic-report.plugin.ts
- packages/plugins/src/plugins/re-rehearse.plugin.ts
- packages/plugins/src/plugins/utils.ts
- packages/plugins/test/__snapshots__/re-rehearse.plugin.test.ts.snap
The `re-rehearse` plugin removes existing comments with `@rehearsal` without including `\n`.
This PR fixes the issue and `@rehearsal` comments will be removed correctly (including `\n` at the end).
Fixes https://github.com/rehearsal-js/rehearsal-js/issues/1246
> fix: do not add empty lines before @ts-expect-error on sequential runs

- packages/codefixes/src/codefixes.ts
- packages/codefixes/src/codefixesMessages.json
- packages/codefixes/src/fixes/annotateWithStrictTypeFromJSDoc.ts
- packages/codefixes/src/glint-codefix-collection.ts
- packages/migrate/test/__snapshots__/migrate.test.ts.snap
- packages/migrate/test/fixtures/project/src/gts/with-strict-types.gts
- packages/migrate/test/migrate.test.ts
Co-authored-by: @egorio 
- Added `AnnotateWithStrictTypeFromJSDoc` to the list of `glintCodeFixes`.
- Refactored `AnnotateWithStrictTypeFromJSDoc` to support a glint diagnotics.
- This is not ideal, but it works. Ideally we shouldn't muddle an existing CodeFix for TS with glint specifics.
- Removed  diagnostic `95009` from `annotateWithStrictTypes.messages` in `packages/codefixes/src/codefixesMessages.json`.
```
"annotateWithStrictTypeFromJSDoc": {
"title": "Annotate Strict Types From JSDoc",
"description": "Annotates code with the only strict types from the declared JSDoc comments. Strict replacement for annotateWithTypeFromJSDoc",
"diagnostics": [80004],
-    "messages": [95009],
+    "messages": [],
"builtIn": true
},
```
This diagnostic message was causing the our strict types fix to …
> feat: add strict type from jsdocs to .gts files

- packages/cli/src/commands/fix/tasks/convert-task.ts
- packages/cli/src/commands/fix/tasks/convertWorker.ts
- packages/cli/src/helpers/report.ts
- packages/cli/src/types.ts
- packages/cli/test/commands/fix/__snapshots__/fix.test.ts.snap
- packages/migrate/src/migrate.ts
- packages/reporter/src/reporter.ts
- packages/service/src/plugin.ts
- packages/smoke-test/test/commands/__snapshots__/fix.test.ts.snap
- packages/utils/src/cli.ts
- packages/utils/src/index.ts
- packages/utils/src/progress-bar.ts
- packages/utils/test/cli.test.ts
- packages/utils/test/progress-bar.test.ts
Closes #1239 
Adds progress bar during type inferring and duration takes to process files at the end.
```
✔ Initialize
✔ Analyzing project dependency graph ...
⠼ Infer Types
› starting...
› preparing files ...
› [--------------------] 0/4 files | ETA: **:**:**
processing file: /src/GreetingHeader.ts
› [=====---------------] 1/4 files | ETA: 00:00:06
processing file: /src/App.ts
› [==========----------] 2/4 files | ETA: 00:00:05
processing file: /src/SimpleComponent.ts
› [===============-----] 3/4 files | ETA: 00:00:02
processing file: /src/index.ts
✔ Types Inferred
Duration: 00:09
... errors caught by rehearsal
```
> feat: progress & duration in the CLI

- packages/codefixes/src/fixes/glint/addMissingArgToComponentSignature.ts
- packages/codefixes/src/fixes/glint/glint-parsing-utils.ts
- packages/migrate/test/__snapshots__/migrate.test.ts.snap
- packages/migrate/test/fixtures/project/package-lock.json
- packages/migrate/test/fixtures/project/package.json
- packages/migrate/test/fixtures/project/src/gts/signatures/template-only/with-toc.gts
- packages/migrate/test/migrate.test.ts
- Adds support for the convenience TOC type from `@ember/component/template-only`.
- Passes found type identifier to glint methods.
- Adds `@types/ember__component` to migrate test fixture, allows for test for toc to not show rehearsal TODOS.
- Depends on #1278
- This should close out the work to complete #1227
> feat(codefix): support TOC type from `@ember/component/template-only`

- package.json
- packages/migrate/package.json
- packages/migrate/test/fixtures/project/package.json
- packages/migrate/test/fixtures/project/packages/moo/package.json
- packages/plugins/package.json
- packages/service/package.json
- packages/service/src/glint-service.ts
- packages/smoke-test/package.json
- packages/smoke-test/test/fixtures/ember_js_app/package.json
- packages/smoke-test/test/fixtures/glimmerx_js_app/package.json
- packages/test-support/fixtures/ember/app-ts-template/package-lock.json
- packages/test-support/fixtures/ember/app-ts-template/package.json
- pnpm-lock.yaml
Currently when any rehearsal command is used, the following error is emitted:
```       ^^^^^^^^^
SyntaxError: The requested module 'vscode-uri' does not provide an export named 'default'
```
There appears to have been api change in vscode-uri that rehearsal picked up as part of a package update.  This diff fixes the issue by using the exported URI function from vscode-uri.
Note, error will only occur if consuming app is on vscode-uri 3.0.8.  However, we should keep up with the package upgrade and ensure that no consumers are blocked by the above issue.
Note, we also need to bump glint/core dependency which contains the same issue being fixed in this diff: https://github.com/typed-ember/glint/blame/main/packages/core/src/language-server/util/index.ts
- `pnmp vitest -u` passes when run on …
> (fix) Updating glint-service to use the exported `URI` method from vscode-uri
